### ISSUE TITLE
Reopen #998

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#1009]
See #998.

MOAITextLabel:getBounds is returning the boundaries of the text. 
MOAITextLabel:getDims is returning the width and height of the text. 
MOAITextLabel:inside and determines whether it is in the text. 

In either case, you will need to perform a forceUpdate function, returns the old value. 
Also, a big change from V1.6. 
If you want to get the size, it is no longer able to be handled in the same way as a MOAIProp.

**Comment by Vavius** [comment]
I see two ways: 
1) getBounds, getDims, inside uses text designer width or height or both based on rectLimits setting. If no limits specified then fallback to stringBounds
2) Respect boundsOverride from MOAIProp

Using larger bounds from the whole text rect can cause unnecessary draw calls. If textLabel will respect boundsOverride we can keep using stringBounds as default bounds. Old behavior can be achieved in Lua with getRect (replacement for getBounds, getDims). If inside() is needed, then you set bounds override.

**Comment by makotok** [comment]
Thank you. I came up with how to fix. 
Take a look because it later pull request.

**Comment by halfnelson** [comment]
pull request is done, is this issue resolved now @patrickmeehan
