### ISSUE TITLE
Please update android-cmake for android-ndk-r10c

### ISSUE THREAD

**Issue by khanhbui** [moai/moai-dev#1037]
I have been trying to build for android and I got this error message:

CMake Error at host-android/android.toolchain.cmake:819 (list):
  list index: 17 out of range (-17, 16)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.0.0/share/cmake/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:9 (project)

I'm using the '1.5-stable' branch and 'android-ndk-r10c'. I have tried the 'ndk-r10c' of android-cmake and it works.

**Comment by halfnelson** [comment]
done for 1.7, not using cmake anymore for android builds, 1.6 had this fix too.
