### ISSUE TITLE
triggering the assert, file ZLBitBuffer.cpp

### ISSUE THREAD

**Issue by ghost** [moai/moai-dev#1040]
- Linux 3.13.0-24-generic #47-Ubuntu SMP x86_64 x86_64 GNU/Linux
- gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
- Branch develop.
  Example:

``` C++
ZLBitBuffer.cpp:417: void ZLBitBuffer::Test(): Assertion `check_bin ( buffer, "00010011001110011000000111000000" )' failed.
```

Assert lines: 417, 421, 431, 435

**Comment by halfnelson** [comment]
this is pretty old ticket, Does this still happen?
