### ISSUE TITLE
Android Gradle Flags Processing Bug

### ISSUE THREAD

**Issue by fritzy** [moai/moai-dev#1064]
1. run bin/android.sh
   2 in util/ I run ./moaiutil host-android-gradle and create a host for Android Studio -- great!

https://github.com/moai/moai-dev/blob/develop/host-templates/android/studio/MoaiTemplate/app/moai.gradle#L28-L31
causes "flags" to be "=1" which breaks the ndk compile process.
replacing flags with "" prevents the bugs, and I'm able to compile and run.
Perhaps this only happens when no modules have been specified.

**Comment by halfnelson** [comment]
fixed
