### ISSUE TITLE
MoaiGrid does not work on android!!

### ISSUE THREAD

**Issue by ghost** [moai/moai-dev#1103]
Hello!
I've been testing my game which uses MoaiGrid for tilemaps and it does not show me anything.At first I thought it's something wrong with my code or something.Then I grabbed the grid samples which come with moai and they do not work as well.
I do not get any kinds of errors or freez inside the game or in log cat.I'd suggest you to try for yourself and see!

This one does not work too : /home/vlad/moai-dev/samples/deck/tilemap-wrapping/
Edit 1: Everything seems to work just fine!

**Comment by ghost** [comment]
This is one of the reasons why Moai should delete all it's high level stuff because it gets more complicate to handle them on different devices.In my opinion a big refractory should be made in Moai to delete all the unecesarry things and let the users make the features they need inside Lua.

**Comment by halfnelson** [comment]
did this get resolved?

**Comment by ghost** [comment]
It did by cloning again stable 1.5
