### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by voidloop** [moai/moai-dev#1105]
I've noticed that ./bin/build-linux.sh is not an executable file by default. And the file name is not "./bin/build-linux-sdl.sh". 
Thank you.

**Comment by voidloop** [comment]
After building Linux host where is the moai executable file? Is structure of directories changed? 

install_path/moai-dev/release/linux/host-sdl/x64/bin

doesn't exist ...

**Comment by ghost** [comment]
Go to cmake - build - host-sdl

**Comment by voidloop** [comment]
OK. Thank you, but:

cd moai-dev/cmake/hosts/host-linux-sdl
cmake .
make

and this error happened:

moai-dev/cmake/hosts/host-linux-sdl/../../../3rdparty/openssl-1.0.0m/include/openssl/mdc2.h:69:2: error: #error MDC2 is disabled.
 #error MDC2 is disabled.

**Comment by ghost** [comment]
If you want to build for linux then go into moai-dev - bin run ./build-linux-sdl.sh. And after that go into cmake folder - bin and run :  make moai-sim/fast and this means it will recompile the sim folder,in case you want to modificate stuff.

**Comment by voidloop** [comment]
OK, but if I follow the download instructions of the README.md 

```
git clone https://github.com/moai/moai-dev.git
cd moai-dev
git submodule init
git submodule update
```

and 

```
cd moai-dev
./bin/build-linux-sdl.sh
```

the file doesn't exist!

```
zsh: no such file or directory: ./bin/build-linux-sdl.sh
```

where is this file?

**Comment by ghost** [comment]
What version of moai are you using? I'd recomand to download 1.5-stable. Use git checkout 1.5-stable

**Comment by voidloop** [comment]
```
# git branch                            
* develop 
```

**Comment by ghost** [comment]
Change it to 1.5-stable,is what most people use.Develop and 1.6 are different from the prev versions of moai.

**Comment by voidloop** [comment]
It works. Thank you.

```
# cd moai-dev
# git checkout -b 1.5-stable origin/1.5-stable
# ./bin/build-linux-sdl.sh
# ls release/linux/host-sdl/x64/bin/
moai
```

**Comment by ghost** [comment]
If you want you can join us on irc: moai on freenode 

Trimis de pe iPhone-ul meu

Pe 08.04.2015, la 13:15, "Marco E." notifications@github.com a scris:
