### ISSUE TITLE
ready to code equipment

### ISSUE THREAD

**Issue by movingelectrons** [moai/moai-dev#1108]
I've played with moai a few years ago and finally have time to get back into it, but I have all new equipment, including software.  i've spent a good day or two trying to get moai to run and still haven't gotten there yet, got android studio working and building some really simple hello world app and button / alert dialog but thats it so far.

to save myself from giving up does anyone have old working hardware or maybe a disk image of working complete software disk image or bootable live dvd/cd/sdcard/thumbdrive they would like to give me?

also are there any events planned for the future? i was at the one in seattle f5 a few years ago would be cool if there was another one

**Comment by halfnelson** [comment]
linux windows or mac. Check out http://halfnelson.github.io/moaicli/ which was created for exactly this reason

**Comment by movingelectrons** [comment]
mac, linux, windows.  in that order, i only have pc equipment right now though

**Comment by halfnelson** [comment]
Hope you got it all going.
