### ISSUE TITLE
Add doxygen post-processing to generate syntax files for popular IDEs

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#111]
People would like Moai coe completion and syntax highlighting for their favorite IDEs:

http://getmoai.com/forums/auto-generating-a-moai-api-lua-file-for-intellij-t400/

**Comment by plandem** [comment]
i already have parser/builder for that files. right now working on builder of 'quick-help'  for IDE. When i will finish with 'quick-help' i can send you my parser/builder. Though  it coded in PHP as console script.

**Comment by patrickmeehan** [comment]
That would be great! (And sorry for the slow response.)

I'm moving this task to Trello. Just email if you're still available to help out.
