### ISSUE TITLE
Can't compile under Arch Linux.

### ISSUE THREAD

**Issue by ghost** [moai/moai-dev#1118]
[100%] Linking CXX executable moai
../zlcore/zlvfs/libzlvfs.a(headers.cpp.o): In function `zl_tmpnam':
headers.cpp:(.text+0xfd1): warning: the use of`tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: ../third-party/sdl2/libSDL2.a(SDL_x11events.c.o): undefined reference to symbol 'XPending'
/usr/lib/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
host-sdl/CMakeFiles/moai.dir/build.make:168: recipe for target 'host-sdl/moai' failed
make[2]: **\* [host-sdl/moai] Error 1
CMakeFiles/Makefile2:2609: recipe for target 'host-sdl/CMakeFiles/moai.dir/all' failed
make[1]: **\* [host-sdl/CMakeFiles/moai.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2
[omx@omx moai-dev]$ 

Using Moai 1.5-stable.

**Comment by halfnelson** [comment]
looks to be missing one of the x11 deps, 1.7 is more stable, checkout moai/moai-community repo for linux builds, they have been removed from this repo for now.
Thanks for the report
