### ISSUE TITLE
Some sample does not work.(moaisdk-osx-1.6.11)

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#1119]
I ran the binary of moaisdk-osx-1.6.11.
Most of the samples were able to run! Thank you.

However, The following sample does not work.
- gfxQuadListDeck2D
- gfxQuadListDeck2D-grid
- gridDeck2D

**Comment by halfnelson** [comment]
hopefully fixed with 1.7, quick test with 1.7 html host shows them all working, so the core engine stuff seems sorted now.
