### ISSUE TITLE
No submodules listed after cloning ?

### ISSUE THREAD

**Issue by ishan1608** [moai/moai-dev#1120]
I am trying to setup moai on Ubuntu.
In the README https://github.com/moai/moai-dev/blob/develop/README.md
Instructions for cloning are these:

```
git clone https://github.com/moai/moai-dev.git
cd moai-dev
git submodule init
git submodule update
```

However after cloning when I run : _git submodule init_ , it doesn't do anything.
So I ran these: _git submodule_ , _git submodule status_. Both resulted with no output.
Please Help

**Comment by halfnelson** [comment]
Develop branch has no submodules anymore. 1.5-stable probably does which I
think the guide was written for

**Comment by ishan1608** [comment]
Where can I find the build instructions for the latest stable version or the develop branch itself.
I am sorry to bother you with this; but I am very new to moai and am trying to setup and run moai for the very first time.

**Comment by halfnelson** [comment]
http://moaiforge.com/community-docs/docs/sdk/moai-sdk-desktop-basics.html has some info for using the sdk based on moai/moai-community repo
