### ISSUE TITLE
moaiutil localize command

### ISSUE THREAD

**Issue by seclorum** [moai/moai-dev#1124]
Right now, moaiutil only builds the moai bin if you're on OSX.  It should 'just do it' for all platforms. This is an issue for tracking and gaining test results.

For example, currently in $MOAI_SDK_HOME/util/moaiutil

```
if ! [ -x "$(which moai)" ]
then
    pushd $MOAI_SDK_HOME/xcode/osx > /dev/null
    ./build.sh
    popd > /dev/null
fi
```

This means we need to add developer-platform projects (Linux/VisualStudio/XCode) that will produce this binary - if these 'harness projects' already exist for other developer platforms, moautil should be extended to produce those binaries for each platform on demand.

What would be ideal is if new developers could just clone the repo, run moaiutil once, whatever their platform, and get a fresh developer-local moai binary for their uses produced automatically for them.

**Comment by halfnelson** [comment]
this needs to be moved to the moai-community issue tracker, might already be working for at least windows now
