### ISSUE TITLE
Pito builds doxygen documentation incorrectly. 

### ISSUE THREAD

**Issue by seclorum** [moai/moai-dev#1170]
From: http://getmoai.com/forums/alive-or-dead-t3258/?sid=837fd3f9dc4be03f20bf81e6f73e6769
- Pito builds doxygen documentation incorrectly. Class pages are generated, but they don't have the method list at the top.

**Comment by halfnelson** [comment]
seems to be working now: http://moaiforge.com/api-docs/latest/class_m_o_a_i_action.html
