### ISSUE TITLE
In-App purchase can "hang"

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#129]
Initiate a purchase. Press the home button. 

App gets stuck in a state where it's waiting for a Market response.

**Comment by seanzipline** [comment]
Moving this out of 1.0. It's a bit of a corner case and, unfortunately, not under our control - we simply do not get any response from the Market when the user does this. If we do anything, it may have to be in lua.

**Comment by patrickmeehan** [comment]
trello
