### ISSUE TITLE
MOAIFileSystem.listFiles and listDirectories don't work with ZipFS

### ISSUE THREAD

**Issue by jlytledistinctdev** [moai/moai-dev#130]
I am using MOAIFileSystem.listDirectories and listFiles in my project, but when I'm running in the Android host with ZipFS, the game crashes outright when either of these functions is called. If you can't immediately reproduce this, please let me know and we can figure out a repro case, but I believe it just happens all the time.

**Comment by danadrew** [comment]
See sample in: samples / test / zipfs-list-files

listDirectories appears to work in my test, however listFiles crashes as reported. There appears to be an issue with mounting the zip directory because it also failed to open a file that was contained in the directory.

**Comment by patrickmeehan** [comment]
OK, should be fixed now.
