### ISSUE TITLE
MOAIFileSystem.checkFileExists always returns true with ZipFS

### ISSUE THREAD

**Issue by jlytledistinctdev** [moai/moai-dev#131]
In the Android host, using ZipFS, if you call MOAIFileSystem.checkFileExists on a file that doesn't exist, it returns true.

**Comment by danadrew** [comment]
I wasn't able to reproduce this on Windows, it's possible this is an Android only bug? I added a sample to demo that it is working in samples / test / zipfs-check-file-exists. It is returning false correctly when a non-existent file is called.

**Comment by patrickmeehan** [comment]
Sean, check this out when you have a sec. I _think_ we fixed it.

**Comment by jlytledistinctdev** [comment]
This only reproduces on Android, in my experience. It's only when you're using ZipFS to mount your files in the Android host.

**Comment by adamvillalobos** [comment]
Confirmed this on Android, doesn't seem to happen. Closing for now.
