### ISSUE TITLE
Untz sounds have delay when played in Windows host

### ISSUE THREAD

**Issue by jlytledistinctdev** [moai/moai-dev#133]
I am playing sounds (OGG files specifically) in the Windows host via Untz, and there is a slight delay before each one when compared with the Android, iOS, and OSX hosts.

**Comment by danadrew** [comment]
Added a sample in integration branch: samples / test / sound-untz

Press any button to print some text to the console and play the sound. You will notice that the sound plays a short time after the button is pressed and text is printed.

**Comment by patrickmeehan** [comment]
Sean, could  you get this to Bob? You sent him a batch of other bugs, right?

**Comment by seanzipline** [comment]
Any repro instructions?

**Comment by danadrew** [comment]
There should be a repro on the integration branch in: samples / test / sound-untz

The instructions should be in a comment above, basically just run the sample and press any button on the keyboard and it'll play a sound. There will be a brief, but noticeable, delay before the sound is played. If you open the audio sample in another program to play it there is no delay at the beginning, so I don't believe that pause is part of the actual sound file.

**Comment by jlytledistinctdev** [comment]
This repros all the time on every sound. You can also clearly hear the difference by running your same code on the iOS, Android, or OSX host and not hearing the delay.

**Comment by patrickmeehan** [comment]
trello

**Comment by ezraanderson** [comment]
could some one comment on how to fix or post the fix for this.

**Comment by frantufro** [comment]
We pushed the bugfix to the next major release since we're busy with other stuff right now, if you can fix it we'd ask you to send us a pull request. Thanks!

**Comment by robertwahler** [comment]
Given that this issue has been closed and this one opened https://github.com/moai/moai-dev/issues/570 it seems to  signal that Untz has no future with Moai.  Has anyone started with OpenAL/OpenSL?

**Comment by ubershmekel** [comment]
JFYI I found this tidbit on the MOAI forums that decreased the delay enough for me:

```
MOAIUntzSystem.initialize(44100, 1000)
```

instead of

```
MOAIUntzSystem.initialize()
```
