### ISSUE TITLE
MOAIFont:loadFromTTF may not working on three-dee branch

### ISSUE THREAD

**Issue by kengonakajima** [moai/moai-dev#138]
I tested font samples on three-dee branch on osx host on Lion, and I got:

samples/basics/font-bitmap : OK.
samples/basics/font-colors : NG.  no fonts show up
samples/basics/font-serialize :  NG.  loadFromTTF fails internally and getImage fails
samples/basics/font-texture-colors : OK. using PNG font, not TTF
samples/basics/font-ttf : NG. no fonts show up
samples/basics/font-utf8 :  NG. no fonts show up

all NG samples are using loadFromTTF.  Some issues may in loadFromTTF?

Please investigate it.

**Comment by patrickmeehan** [comment]
This seems to have been fixed during the text system rewrite for 1.0.
