### ISSUE TITLE
MOAIMesh:setPenWidth() is not working in three-dee branch

### ISSUE THREAD

**Issue by kengonakajima** [moai/moai-dev#139]
MOAIMesh:setPenWidth() is not working.

You can reproduce it at:

https://gist.github.com/1871952

MOAIGfxDevice.setPenWidth seems not working too. (also in the same gist)

**Comment by adamvillalobos** [comment]
Sample seems to be missing call to MOAIGfxDevice.setPenColor ( 1, 1, 1, 1 )

Sample is also too dated to be used in master, but I checked it against samples/deck/scriptDeck which uses the pen color and seems to work fine.

**Comment by kengonakajima** [comment]
thanks!
