### ISSUE TITLE
io.popen crashes Moai

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#156]
http://getmoai.com/forums/post2550.html#p2550

**Comment by danadrew** [comment]
Added a sample in: samples / test / popen

The sample code is exactly what he posted on the forum, the read line is the one that is crashing, not the popen itself.

**Comment by patrickmeehan** [comment]
OK, this seems wot work on Windows. Needs to be tested on other platforms. The problem was that there was no zipfs wrappers for popen and pclose, so the system implementations were being used, which return file handles incompatible with zipfs.

**Comment by danadrew** [comment]
It is working on Windows but I'm leaving the issue open til I can get a build running on a device.
