### ISSUE TITLE
MOAITextBox.nextPage () blink bug

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#158]
If you make a text box and call setReveal to reveal only a portion of the page, then call nextPage, the remainder of the page will blink on the screen for a brief moment before the next page is brought up.

**Comment by danadrew** [comment]
Sample to demo this has been added in: samples / test / textbox-page-blink

**Comment by patrickmeehan** [comment]
OK, this should be fixed now.

**Comment by danadrew** [comment]
Appears to be working.
