### ISSUE TITLE
TextBox - revisit ignoring white space with different text alignments

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#160]
Currently white space at the end of lines is always ignored and white space at the beginning of lines is always printed, regardless of the justification. It might make sense to make it so that when the text is right justified it would flip it and ignore white space at the beginning and print white space at the end, as well as making it so no white space is ignored if it's center justified.

Verify photoshop's implementation to match that.

**Comment by patrickmeehan** [comment]
trello
