### ISSUE TITLE
Bug when changing font of a TextStyle in a TextBox

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#161]
See repro in integration branch: samples / test / setstyle

In the sample, I create a string of text that utilizes setStyle to create a new default style and one additional style named 'green'. Both styles initially use different fonts. After you press the spacebar, it will attempt to change the font that the default style uses to the same font as 'green', and this is where the bug happens. You will notice that a good portion of apparently random characters will be missing. Pressing spacebar again will return to the original text.

There are several things that make this bug very strange.
1. It only happens if I change the default style after I wait for the spacebar input (lines 55-56). If I move these lines to before the spacebar then it behaves as expected.
2. On line 56 I'm setting a style that is never actually used. Even though the style is never used, without this line the bug does not occur.
3. A small part of the text is using the 'green' style, if I remove this style and have all of the text in the default style, then the bug does not occur.
4. Changing the default font to EBOLA-KI instead of Dwarves (font3 instead of font2) makes the bug not occur.

**Comment by danadrew** [comment]
One additional thing I just found is that the bug does not occur when I add the following lines somewhere before the execution of the setStyleTests() function:

charcodes = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 .,:;!?()&/-'
font2:preloadGlyphs ( charcodes, 24 )

So it appears as though there might be a problem with the automatic loading of glyphs, since preloading them makes it work as expected.

**Comment by patrickmeehan** [comment]
OK, I think this is fixed. Check it out.

**Comment by danadrew** [comment]
Seems to be working fine now.

**Comment by danadrew** [comment]
This bug is broken once again.
