### ISSUE TITLE
three-dee: use USBox instead of USRect in MOAIMesh::GetBounds

### ISSUE THREAD

**Issue by kengonakajima** [moai/moai-dev#162]
USRect doesn't contain Z information so it causes incorrect view frustum culling when a mesh has specially flatter or longer shape.

To reproduce it, use this:

https://github.com/kengonakajima/snippets/tree/master/moai/cull_bug

**Comment by patrickmeehan** [comment]
Sorry for leaving this so for such a long time. Turns out we had a regression in MOAIInexBuffer after 1.0 as well. The bounds all return USBox now and MOAIIndexBuffer is fixed. I downloaded and ran your test case - thanks for sending it.
