### ISSUE TITLE
Multiple sizes and fonts in a multi-page text box bug.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#164]
See sample in: samples / test / setstyle3

**Expected:**
Text should display in the proper order when a text box contains multiple pages using multiple styles of variable sizes and fonts.

**Actual:**
Occasionally the first part of what should appear on the second page will appear in the middle of the first page.

**Repro Steps:**
1. Create multiple different text styles using different fonts and sizes.
2. Create a text box that has text that will span multiple pages, utilize all of the created styles.
3. In some cases text that should appear on the second page will appear in the middle of the first page.

**Additional Info:**
In the sample I turned on debug drawing. The text that is appearing on the first page is extending outside of the textbox bounds and also doesn't appear to have any debug drawing on it.

The bug did not happen on every page when I extended the text to go for more than two pages. So it doesn't always happen on every page, but it does always happen on the sample provided.

Making all the text the same size or the same font appeared to cause the bug to not occur.

**Comment by patrickmeehan** [comment]
I think my fix for issue #168 also fixed this issue. I ran test/setstyle3 and didn't see anything out of place.

**Comment by danadrew** [comment]
Yup, this issue appears to be resolved.
