### ISSUE TITLE
Using a style that doesn't exist causes a crash.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#166]
See sample: samples / test / textbox-bad-text2

**Expected:**
If a style tag is used for a style that doesn't exist, it should be ignored and probably output an error/warning.

**Actual:**
The application crashes in a non-obvious way.

**Reproduction Steps:**
1. Create a text box and have the text use a style that you don't set up.
2. The application will crash and give no information as to why.

**Comment by patrickmeehan** [comment]
So the bug here wasn't that the style doesn't exist, it was that there was no valid default style for the text box.

**Comment by danadrew** [comment]
Seems to be working from my tests.
