### ISSUE TITLE
setHighlight doesn't always work when not using a style.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#174]
See sample: samples / test / textbox-highlight

**Expected:**
setHighlight should highlight the text even if I set up the font using setFont and setTextSize.

**Actual:**
It sometimes does not highlight the words.

**Reproduction Steps:**
1. Set up a text box with some text, use textbox:setFont and textbox:setTextSize instead of setting up a default style.
2. Immediately after that, try to highlight part of the text.
3. The text will not be highlighted.

**Additional Info:**
The highlighting appears to work fine if I use setStyle to create the default style, it only breaks when I use setFont and setTextSize. The highlighting will work if you do it later on, for example in the sample I have it call the exact same setHighlight after you hit the spacebar and it will highlight the text at that time.

**Comment by patrickmeehan** [comment]
OK, I rewrote the highlight system. The highlights should now go into effect immediately and persist even after paging.

**Comment by danadrew** [comment]
I've tested this pretty thoroughly and the new system seems to be working as intended.
