### ISSUE TITLE
Words sometimes omitted at the end of text.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#175]
See sample: samples / test / textbox-paging3

**Expected:**
All words should be printed if there's room on the page.

**Actual:**
The last word on the second page in the sample is left off, there is plenty of room for it.

**Reproduction Steps:**
1. Create a text box with text spanning multiple pages.
2. Sometimes the last word will be missing from the last page.

**Additional Info:**
This bug doesn't appear to occur that often, but my repro sample does it 100%. I can't find what's specifically causing it, some text strings do it and some don't.

**Comment by patrickmeehan** [comment]
OK, I think this is fixed now.
