### ISSUE TITLE
Properly handle orientation and screen size changes in Android

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#177]
Ok, so as we just briefly discussed, there is an issue on Android
where sometimes the device tells us that its in portrait mode even
when we've locked it down to landscape in the manifest. This seems to
only occur when the app launches with the screen locked, so the
priority here is not huge.

So, without any hacks in Java, we may end up calling AKUSetScreenSize
(480, 800), followed by AKUSetViewSize (480, 800), AKUSetViewSize
(800, 400). Depending on timing conditions with scripts running, this
can cause WT to end up in a fucked-up portait mode in landscape.

I will file a bug for post-1.0. In all liklihood, this is going to
require some fixes in Android to detect orientation changes to update
AKUSetScreenSize and then exposing listeners to lua (if they don't
exist already) for WT to react and redraw.

**Comment by patrickmeehan** [comment]
trello
