### ISSUE TITLE
Characters cut short when center justified.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#184]
See sample: samples / test / textbox-center-justified

**Expected:**
Text that is center justified should still display the characters in their entirety.

**Actual:**
Some of the characters appear to be missing a column of pixels on the right side.

**Reproduction Steps:**
1. Create a text box that has center justification.
2. Some of the characters will be cut short.

**Additional Info:**
Probably due to the location of the glyphs being a non-integer.

**Comment by patrickmeehan** [comment]
OK, should be fixed now.
