### ISSUE TITLE
Box2D breaks with 8 vertices.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#189]
See sample in: samples / test / box2d-8-vertices

The sample is just the physics-box2d sample but with 8 vertices instead of 4. When you run it, it gives the error:

BOX2D ERROR: Vertex count 8 is invalid (less than 3 or greater than max)
stack traceback:
        [C] in function 'addPolygon'
        main.lua:60 in main chunk

main.lua:61: attempt to index global 'fixture' (a nil value)
stack traceback:
        main.lua:61 in main chunk

**Comment by danadrew** [comment]
There is some discussion on the issue here: http://getmoai.com/forums/box2d-vertex-count-8-is-invalid-t550/

**Comment by patrickmeehan** [comment]
Your fix was correct. My guess if people are still having problems is that they somehow got the wrong code.
