### ISSUE TITLE
Hyphens don't split up words into multiple tokens

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#191]
For after 1.0

Currently words with hyphens will always be considered one word, so it will not split them onto multiple lines. This could be a problem if a long hyphenated phrase is used, it might leave a lot of white space at the end of a line in order to fit it on the next line, when it should split the words up at the hyphens and allow it to be on multiple lines.

**Comment by patrickmeehan** [comment]
I'm going to change this to a 1.1 feature (instead of a bug).

**Comment by patrickmeehan** [comment]
trello
