### ISSUE TITLE
Crash on exit with MOAIPartition.setPlane

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#192]
See sample: samples / test / partition-crash-on-exit

**Expected:**
Should be able to set the plane without causing any problems.

**Actual:**
Setting the plane to either the XZ or YZ planes will cause a crash when you exit the program. The XY plane is the only one that behaves as expected.

**Additional Info:**
When I set the plane to XZ or YZ it doesn't crash during run-time, but the debug drawing on my props is exactly identical to when it is the XY-plane. I'm not sure if this is how it's supposed to behave, I'd think there would be different debug info, so the issue may be related to those planes just not working in the first place.

**Comment by patrickmeehan** [comment]
OK, this should be fixed now.
