### ISSUE TITLE
Look into fp errors on rotations

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#194]
Rotations 360 degrees or -360, etc. do not always produce identity matrix; frequently introduce small fp errors. Look into any ways to better handle these rotations and produce fewer fp errors.

**Comment by adamvillalobos** [comment]
In matrix library

**Comment by danadrew** [comment]
There's an example of the -360 rotation in samples / test / partition-bad-fit

When the prop is rotated -360, the partition level is kicked up to the larger size. When it's rotated 0 it fits the smaller size.
