### ISSUE TITLE
propListForRect doesn't return the props correctly

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#195]
See sample in: samples / test / partition-props-for-rect

**Expected:**
propListForRect should return a list of props that are intersecting with the rect that is inputted.

**Actual:**
Under many conditions it doesn't return the correct list. Sometimes it excludes props that should be included, and sometimes it includes props that should be excluded. You can see both in the sample.

**Additional Info:**
The sample is set up so that it will call propListForRect and print the results when you click the left mouse button, and the rect it uses is a 128x128 box centered around the point you click at. The prop is pre-rotated, scaled, and translated to demo both of the issues with the function.

To demo excluding a prop that should be included:
Click on the left-most corner of the cat. You can actually click on the prop and it will not return that prop.

To demo including a prop that should be excluded:
Click in the area to the top-right of the cat, you can click very far away from the cat in this direction and it will still return the prop, far beyond the extent of the 128x128 box.

If you need help showing where to click, just ask me.

**Comment by patrickmeehan** [comment]
OK, I think this is fixed. Looks like I may have fixed another related bug as well. Turns out the grid boundary calculations were wrong for GatherProps when passed either a box (rect) or a frustum.
