### ISSUE TITLE
Resolve class implementations with same name

### ISSUE THREAD

**Issue by adamvillalobos** [moai/moai-dev#200]
MOAITapyJoy
MOAIAdColony
MOAIFacebook
MOAINotifications
MOAICrittercism

**Comment by patrickmeehan** [comment]
OK. See my example implementation of MOAIHttpTask and MOAIUrlMgr. In the engine there is MOAIHttpTaskCurl and MOAIHttpTaskNaCl. There is also MOAIUrlMgrCurl and MOAIUrlMgrNaCl. In moai.lua I have added an alias with the line:

MOAIHttpTask = MOAIHttpTaskCurl or MOAIHttpTaskNacl

That will simply use whichever implementation is registered. If both are registered then it will use the first implementation. 

For documentation purposes you can create a base class (as I've done with MOAIHttpTaskBase) if you think doing so is appropriate. Alternatively, just document each implementation independently.

I removed MOAIApp from the list as I'm planning to refactor MOAIApp later today.
