### ISSUE TITLE
Mobile 3rdparty SDK locations should be version independent

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#206]
Since libraries like Facebook, AdColony, Crittercism, etc. are likely to be upgraded fairly frequently, it would be beneficial for their locations in 3rdparty to NOT include version information. For example, 3rdparty/adcolonyiOS-197 should be 3rdparty/ios/adcolony with a version.txt file indicating the currently integrated version. That way, changes to projects, SDK bundling, etc. can be minimized.

**Comment by patrickmeehan** [comment]
I disagree. You have to change the projects anyway. I'd like us to keep the status quo on this one.
