### ISSUE TITLE
Implement alternatives to UUID

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#226]
Expose multiple methods of managing identifies through MOAIUnique. Apple has forbidden use of the UUID, so we need a random, guid-based method as well as a consistent MAC address based method. The former is for anonymous identification scoped to an app, the latter is to identify hardware across multiple apps installed on the same device.

**Comment by adamvillalobos** [comment]
Added method to get MACAddress as well as OpenUDID to iOS
