### ISSUE TITLE
FacebookIOS is documented, but source documentation is AWOL

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#230]

**Comment by patrickmeehan** [comment]
Turns out the docs for MOAIWebVewIOS are missing as well.

**Comment by patrickmeehan** [comment]
New theory: header guards could be the culprit. I was looking at this with Dana and noticed that the header guards for a lot of the 'IOS' headers are wrong. For example, MOAIWebViewIOS uses:

#ifndef MOAIWEBVIEW_H

It should be:

#ifndef MOAIWEBVIEWIOS_H

Not sure if doxygen parses and understands preprocessor directives. I'm going to fix these headers and see if that helps. (The headers need to be fixed anyway.)

**Comment by patrickmeehan** [comment]
Fixed the header guards. Run doxygen and see if this was the problem.

**Comment by patrickmeehan** [comment]
trello
