### ISSUE TITLE
Multitouch events being lost on device

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#24]
Josh Lytle reported that certain touch events appear to get dropped on iOS and Android in spite of the internal event queue. This needs to be investigated and fixed.

**Comment by seanzipline** [comment]
Adam - load-balancing to you since you worked on the internal queue stuff.

**Comment by adamvillalobos** [comment]
As discussed this is somewhat working as intended ( input state for polling is cumulative ). Solution to this will be the result of issue  #210
