### ISSUE TITLE
Wrapper for simplifying calls to Moai Cloud

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#241]
Nice to have something higher level than MOAIHttpTask for talking to Moai Cloud. Probably implement in moai.lua.

**Comment by pygy** [comment]
I'm reviewing the documentation, and this would make things more clear. 

Something along these lines?

```
Cloud = MOAICloud.new()
Cloud:setService "username/service"
Cloud:setKeys(public,private) -- if set, sign the requests automatically
Cloud:GET {some=param} -- or POST: URL encode, sign if needed and and execute the request.
```

Similar libraries for other languages/engines would also be useful (I could write a few).

**Comment by makotok** [comment]
MOAI Cloud ended. Close.
