### ISSUE TITLE
Standard deck/font shaders have improper precision for colorVarying

### ISSUE THREAD

**Issue by ckohnert** [moai/moai-dev#247]
The default vertex shaders MOAI*Shader-vsh.h do not explicitly declare precision for varying values (e.g. colorVarying). The fragment shaders expect LOWP in some cases (again, colorVarying), so there is a huge performance hit doing the implicit precision conversion at runtime (especially for large fillrate-limited scenarios like blending fullscreen quads).

Fix: explicitly declare them LOWP so they match the fragment shader(s).

E.g.

```
varying LOWP vec4 colorVarying;
```

**Comment by patrickmeehan** [comment]
My goodness. You are the man, Chris. Thank you so much for tracking this down! We owe you many beers...

**Comment by patrickmeehan** [comment]
Got these in the latest pull request.

**Comment by ckohnert** [comment]
Heh heh. May have to take you up on that some day. ;)

C
