### ISSUE TITLE
Debug drawing for text boxes is off.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#252]
See sample in integration: samples / test / textbox-debug

The debug drawing is off, but the text is still displaying in the right location.

This was broken in this commit: https://github.com/moai/moai-dev/commit/f64e256eb4cc2f45cb5b1d2cbf8af4c17ec116b2

**Comment by patrickmeehan** [comment]
Tuns out this was fixed when the transform caching bug was fixed.
