### ISSUE TITLE
MOAITextBox.clearHighlights doesn't work

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#256]
See sample in integration: samples / test / textbox-clear-highlights

When clearHighlights is called, there is no visible change on the text box. In the sample, no highlights should be displayed because they are being cleared immediately.

**Comment by patrickmeehan** [comment]
Looks like the problem was just in the sample. 'clearHighlight' was being called instead of 'clearHighlights.' I added the missing 's' and that seemed to do the trick.

**Comment by danadrew** [comment]
I made a mistake making the sample, but revised the sample to show a different bug. When clearing the highlights, they don't update on-screen immediately, it only updates after the textbox is redrawn, such as by paging.

In the new sample, the highlights get cleared after pressing space bar, then the page is changed (only 1 page) after pressing space bar again.
