### ISSUE TITLE
Objects displayed in wrong location when viewport and window sizes aren't equal.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#259]
See sample in integration: samples / test / picking

Reported at: http://getmoai.com/forums/moaiviewport-positioning-bug-t667/

This behavior is new as of 1.0, tested on legacy build and it works fine.

This sample is the input-picking sample with modified window size to be larger than the viewport. The cats seem to be displayed lower than they should be, as clicking much higher activates them. Clicking on the cats doesn't pick the objects.

**Comment by patrickmeehan** [comment]
This appears to have been fixed by some other changes.
