### ISSUE TITLE
Implement inheritable scissor rectangle

### ISSUE THREAD

**Issue by adamvillalobos** [moai/moai-dev#268]

**Comment by patrickmeehan** [comment]
The thinking on this now is to do a separate MOAIScissorMask object that can be chained in a hierarchy. The masks will not be props, but may be referenced by props to use when drawing and doing hit detection. The scissor mask will act like a billboard. Later can extend the concept using the stencil buffer to support 3D shapes as masks and bitmaps as masks.

**Comment by patrickmeehan** [comment]
This is a dup of the MOAIScissorRect task.
