### ISSUE TITLE
Crash when rebuildKerningTables is called

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#285]
See example in integration branch: samples / test / kerning-crash

If you call rebuildKerningTables, it will crash.

**Comment by patrickmeehan** [comment]
OK, the crash is fixed but it remains to be seen if the font actually loads the kerning when following this code path. (Also, I'm not planning on triggering a textbox layout on kerning reloads - just so you know.)

**Comment by danadrew** [comment]
The same error that was causing the kerning table to be created incorrectly in the BuildKerning function was also in the RebuildKerning function, so I corrected it there also, should be good now.
