### ISSUE TITLE
affirmPath doesn't work after mounting a virtual directory

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#287]
See sample: samples / test / filesystem-affirmpath

If you mount a virtual directory and then call affirmPath it will fail to create a directory if it doesn't exist.

**Comment by patrickmeehan** [comment]
Should be fixed, but need to verify on all platforms (just tested on Windows).

Turned out the bug didn't have anything to do with mounting a virtual directory, so that shouldn't be necessary to test. More important, need to make sure it works with absolute and relative paths.

**Comment by patrickmeehan** [comment]
From Glen:

it appears that https://github.com/moai/moai-dev/issues/287
that fix breaks MOAIDataBuffer:save for us on osx
