### ISSUE TITLE
Should input event control be explicitly or implicitly bound to lua?

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#288]
Specifically, should we allow lua to control whether or not events are even collected by the host? For example, in Android, by default we turn off level events - it takes a host source code change to turn them on. Should we allow that to be controlled by lua - perhaps even implicitly in the call to set the callback?

MOAIInputMgr.device.level:setCallback ( onLevelEvent )

**Comment by patrickmeehan** [comment]
trello
