### ISSUE TITLE
Possible bug in tilemap clipping

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#290]
See test/tilemap-clipping for repro.

From Sean Monahan:

Hi Guys,

Thanks again for the help with kerning and animations. Now that that's all resolved I have _another_ issue for you!

Attached you'll find a sample that loads up and displays a tile map. You can use the WASD keys to move the camera and 0 resets the camera to the default position. If you load up the sample and start tapping the D key you'll see the issue immediately: the next tile that is supposed to be displayed for the tile map is not be rendered, leaving an empty space. This gaps grows to a width of 64px (the width of a tile) before the next column is drawn.

I had some trouble when I was first setting up tile maps so this certainly could just be me doing something dumb. Could you take a look and let me know what you think?

This is running on 1.0r3

**Comment by adamvillalobos** [comment]
Closing per email, refer to issue https://github.com/moai/moai-dev/issues/312 for continuation.
