### ISSUE TITLE
MOAIHttpTask does not return content unless there is a 2xx code

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#293]
From hsuifan at Red Robot Labs:

hsiufan@redrobotlabs.com: i noticed the http apis in moai don't return content unless its a 2xx status code
hsiufan@redrobotlabs.com: and length is always 0

**Comment by patrickmeehan** [comment]
So this appears to be a libcurl problem. I suspect that libcurl wants us to manually handle things like 1xx and 3xx response codes. Bumping this issue to a future release for further investigation.

**Comment by patrickmeehan** [comment]
trello

**Comment by Qard** [comment]
I'm also having issues with this, which has completely halted our development as we are working with an external web service that responds to input validation errors with 400 codes. We need to be able to parse their response json to determine what the error was so we can notify the user.

After looking at the code, it seems to just be a single line causing it to halt; https://github.com/moai/moai-dev/blob/master/src/moaicore/MOAIHttpTaskCurl.cpp#L115

As far as I can tell, simply setting CURLOPT_FAILONERROR to 0 would fix it.
