### ISSUE TITLE
Crash when using async file io

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#297]
Crash manifests during async file io torture test. While a file is being written to, the file system either fails to open the font file or opens it but returns garbage on read. See samples/test/async-io-crash. May need to run a little while before problem occurs. Happens on Windows and OSX. Happens more frequently in release mode.

Need to fix whatever is breaking file io. Also need to harden the text handling code to not crash if a font is or becomes unavailable.

**Comment by adamvillalobos** [comment]
Need to rewrite zipfs to not use the static buffer.

**Comment by patrickmeehan** [comment]
Have tested this now and it appears to be fixed.
