### ISSUE TITLE
Investigate gathering performance information

### ISSUE THREAD

**Issue by adamvillalobos** [moai/moai-dev#300]
-Time CPU execution time of functions
-Collect information about number and types of props drawing
-Track graphics state changes
-Fill rate, is this possible?

**Comment by adamvillalobos** [comment]
For CPU timing:

-Anim Curve
-Attributes
-Scene Sorting
-I/O, HTTP
-Coroutine
-Particles
-Physics
-Sound

Ability to Flag functions in lua to be tracked.

**Comment by adamvillalobos** [comment]
-GC?

**Comment by patrickmeehan** [comment]
trello
