### ISSUE TITLE
Grab latest Moai GUI from Derick

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#309]
http://code.google.com/p/moaigui/downloads/list

**Comment by seclorum** [comment]
I would like to suggest that if you do grab the latest GUI from Derick, we end up using the moai- git repository as the 'place' for it .. one thing that has been confusing is that the contrib/ tree gets out of date pretty fast, so if we can just get a firm repo home for moaigui it would be very helpful - and why not put it into MOAI branch, main?

**Comment by patrickmeehan** [comment]
That's fine by me. I just copy the latest verbatim into contrib. Could fork and update that by sending pull requests. Or just keep a separate github repo. It's nice to have it in the SDK release, but at some point a directory of moai-based projects on our site or wiki might make more sense, especially since we don't test or maintain anything in contrib.

I'm happy to go with whatever you, Derick and the community think is best.
