### ISSUE TITLE
TileDeck2D Y-flips the 0th tile in 'window-style' coordinate system.

### ISSUE THREAD

**Issue by jakerr** [moai/moai-dev#315]
I tried using tileDeck2D with window style viewport. i.e. (0, 0) is at top left, positive-y is down the screen.

I modified the tileDeck2D sample so that a mouse click advances the prop index. When using the window style projection, the tileDeck starts with the 0th tile rendered with the y-axis flipped. However, clicking to advance the prop index, shows the other tiles rendered right-side up.

The SDK basics document mentions when flipping the viewport coordinate system you also need to update the uvs (setUVRect) of your texturedQuads so that they won't be flipped. However TileDeck2D does not have a setUVRect so I guess it is supposed to handle this internally? And it actually seems to do the right thing for the tiles that are not index 0.

here's the patch to the tileDeck2D sample for reproduction.
I tried on latest integration branch to verify that it hasn't yet been fixed. Was still the case as of (967fc4def74773e6c4f473eb2cb1c9f9e5d448a5)

``` patch

---
 samples/deck/tileDeck2D/main.lua |   18 ++++++++++++++++--
 1 files changed, 16 insertions(+), 2 deletions(-)

diff --git a/samples/deck/tileDeck2D/main.lua b/samples/deck/tileDeck2D/main.lua
index ddfc330..16aa257 100644
--- a/samples/deck/tileDeck2D/main.lua
+++ b/samples/deck/tileDeck2D/main.lua
@@ -8,7 +8,8 @@ MOAISim.openWindow ( "test", 320, 480 )

 viewport = MOAIViewport.new ()
 viewport:setSize ( 320, 480 )
-viewport:setScale ( 320, 480 )
+viewport:setScale ( 320, -480 ) -- use negative Y axis
+viewport:setOffset ( -1, 1 ) -- offset projection origin by -1, 1 in OpenGL projection space

 layer = MOAILayer2D.new ()
 layer:setViewport ( viewport )
@@ -17,8 +18,21 @@ MOAISim.pushRenderPass ( layer )
 tileDeck = MOAITileDeck2D.new ()
 tileDeck:setTexture ( "test.png" )
 tileDeck:setSize ( 2, 2 )
-tileDeck:setRect ( -64, -64, 64, 64 )
+tileDeck:setRect ( 0, 0, 128, 128)

 prop = MOAIProp2D.new ()
 prop:setDeck ( tileDeck )
 layer:insertProp ( prop )
+
+function onMouseLeftEvent ( down )
+  if down then
+    --pass
+  else
+    print ( "mouse left up\n" )
+    idx = prop:getIndex()
+    print ("idx is " .. tostring(idx))
+    prop:setIndex(idx + 1)
+  end
+end
+
+MOAIInputMgr.device.mouseLeft:setCallback ( onMouseLeftEvent )
-- 
1.7.9.1+GitX
```

**Comment by jakerr** [comment]
My original experiment was on master where TileDeck2D didn't have `setUVRect`, I just realized that `setUVRect` was added to TileDeck2D in (c9c8ad9b2caceb9b43b05f444ed4b251b124e87c). I tried setting it: `tileDeck:setUVRect ( 0, 0, 1, 1 )` but that caused tile regions to overlap.

**Comment by patrickmeehan** [comment]
It looks like all of the tiles are y-flipped. Try it with this to see what I mean:

![test.png](http://i.imgur.com/brCPG.png)

The reason you're seeing an overlap when you do 0, 0, 1, 1 is that the tile deck uv isn't in pure uv coords. It is a unit rect centered at the origin that is used to scale the actual uv rect for the selected tile being drawn. Setting 0, 0, 1, 1 effectively offsets your tile's uv rect by half a tile diagonally. Try -0.5, 0.5, 0.5, -0.5 and you should see your tiles y-flipped (so the arrow points up).

Re-open this and let me know if you have any more trouble. :)

**Comment by jakerr** [comment]
Thanks a lot Patrick and sorry for my confusion. I had failed to realize that the A tile was the only one that wasn't horizontally symmetrical, making it appear to be the only flipped tile. I'll use your annotated image next time I run into any UV doubts. :)

Also thank you for your tip about the TileDeck UV, makes sense!
