### ISSUE TITLE
Refactor MOAIHttpTask

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#32]
Current cross-platform implementation is a little clunky. Look into replacing implementation object with derived class from abstract virtual MOAIHttpTask.

**Comment by patrickmeehan** [comment]
Refactor for curl is in place. Need to update NaCl implementation to match. Moved away from the opaque pointer implementation to abstract base class + inheritance.

**Comment by adamvillalobos** [comment]
NaCl should be up to date now as well.
