### ISSUE TITLE
Add 3D rotation-specific anim curve type

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#339]
We need a 'fat' anim curve type that represents rotation. Keyframes should be able to specify type of interpolation (euler or slerp) and store their values accordingly.

**Comment by patrickmeehan** [comment]
Just need to return Euler angles for getValueAtTime (), then should be ready for testing.

**Comment by adamvillalobos** [comment]
https://github.com/moai/moai-dev/commit/fbea22052765eddb0ac1669decbc832eeabb951a
