### ISSUE TITLE
Implement attribute accumulator object for animation blending

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#341]
An object has been discussed that will accumulate modifications to its attributes then resolve them using a weighted average. Naming is a challenge: MOAIAttributeAccumulator is no fun to type.

**Comment by ckohnert** [comment]
Btw. This may be better thought of by specifying an option on the anim
curve (assign vs additive).

C

On May 10, 2012, at 9:44 PM, Patrick Meehan
reply@reply.github.com
wrote:

**Comment by patrickmeehan** [comment]
trello
