### ISSUE TITLE
MOAISurfaceDeck2D bug

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#355]
MOAISurfaceDeck2D is the scale of the y-direction does not work properly.
The following points are incorrect.

*Line 234

```
if ( rectHeight > nativeHeight ) {
    yStretchPatchScale = ( rectHeight - ( nativeHeight * this->mYFix )) / ( nativeHeight * this->mYFlex );
}
else {
    yPatchScale = rectHeight / nativeWidth; /* nativeHeight */
    yStretchPatchScale = yPatchScale;
}
```

*Line 258

```
float h = nativeWidth * row.mPercent; /* nativeHeight */
```

Was compiled and correct it.
It was confirmed that the test works.

**Comment by makotok** [comment]
I'm sorry, target file name was incorrect.
Is MOAIStretchPatch2D.

**Comment by patrickmeehan** [comment]
Sorry, this was hiding from me... didn't show up in my filters. This should be fixed now.
