### ISSUE TITLE
Extend vfs path resolving to handle fallbacks

### ISSUE THREAD

**Issue by adamvillalobos** [moai/moai-dev#362]
Setup virtual directories with lists of fallbacks. Also, setup paths with wildcards to fallback on specific filetypes. ( By extension only? )

Provide lua callback to resolve the path as well.

**Comment by patrickmeehan** [comment]
This really seems like something that should be handled in Lua by the game developer/studio framework. i.e.:

texture:load ( resolvePath ( "assets/textures/foo.png" ))

Closing this.
