### ISSUE TITLE
When passing MOAIDataBuffer, optional start/finish arg

### ISSUE THREAD

**Issue by adamvillalobos** [moai/moai-dev#367]
Ability to initialize objects using a subset of the databuffer.

**Comment by patrickmeehan** [comment]
This isn't necessary - can use a MOAIDataBufferStream and seek to the correct location. Just need to make sure that all classes that accept MOAIDataBuffer (such as MOAITexture and MOAIImage) also accept MOAIStream.

**Comment by patrickmeehan** [comment]
Should be supported by the new streams model.
