### ISSUE TITLE
Binary load for MOAIGrid

### ISSUE THREAD

**Issue by adamvillalobos** [moai/moai-dev#368]

**Comment by bobby-oster** [comment]
I would definitely use this feature as we're making a hex-mapped isometric game that has both height levels and multiple levels of zoom - and therefore uses lots of MOAIGrids and TileDecks to track each layer (tile type) at each height level for each level of zoom.  Being able to load in the grids in binary would greatly improve the load and save times.

**Comment by patrickmeehan** [comment]
@bobby-oster Thanks for the comment. We're moving our backlog to Trello. Will try to find a way to make it public again.

**Comment by patrickmeehan** [comment]
trello
