### ISSUE TITLE
Timer callbacks not always called.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#373]
See sample in master branch: samples / test / timer-no-callback
(This sample actually has two repro cases in it, to switch between them set the variable 'test' to either 1 or 2 on the very first line of the .lua file. The first repro is a timer that is using keyframe callbacks, the second repro is a timer that is using loop callbacks.)

Under certain conditions, callbacks are not getting called when they should when a timer's listener is set to listen for MOAITimer.EVENT_TIMER_LOOP or MOAITimer.EVENT_TIMER_KEYFRAME.

EVENT_TIMER_LOOP:
I haven't been able to get a callback to ever be called when a timer is listening for this event.

EVENT_TIMER_KEYFRAME:
A callback is not getting called for keyframe 1 when listening for this event. It is getting called for all other keyframes, however.

**Comment by MattiaFortunati** [comment]
Thanks for having opened an issue on this.
I'm looking forward for the fix, it's really critical for my project. Thanks again.

**Comment by patrickmeehan** [comment]
OK, this should be fixed. That said, the behavior of EVENT_TIMER_LOOP has changed a bit. It will only be triggered for repeating modes. Check out EVENT_TIMER_BEGIN_SPAN and EVENT_TIMER_END_SPAN as alternatives.
