### ISSUE TITLE
Multiple bugs in FileSystem.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#375]
See sample in master branch: samples / test / filesystem-multi-bug
The sample by default will demo all of the bugs. At the top there are two variables you can change to turn off running all of the tests and specify a particular test to run.

There are 4 new bugs introduced to MOAIFileSystem. They are:
1. MOAIFileSystem.affirmPath ()
   If the inputted path includes a .. and no trailing / (ie. "../test"), then the code where the trailing / is added (ZLFileSystem.cpp, line 258) fails and so the path is invalid. This causes affirmPath () to not create the directory like it's supposed to.
   *Note: "../test" works fine with deleteDirectory () and checkPathExists ().
2. MOAIFileSystem.getAbsoluteDirectoryPath ()
   Similar to test 1, if you call getAbsoluteDirectoryPath () with .. in the input path and no trailing /, then the trailing / is not added properly to the returned value. This is not consistent with calling it without a .. and no trailing /. (ie. calling it with "test" will add the trailing / but "../test" will not add it)
3. MOAIFileSystem.listDirectories ()
   listDirectories () returns a table with the proper number of elements, but it fails to append the directory names to each element.
4. MOAIFileSystem.listFiles ()
   Similar to test 3, listFiles () fails to append the file name to each element in the table returned.

**Comment by danadrew** [comment]
Bugs 3 & 4 are not present on ios or osx.

**Comment by patrickmeehan** [comment]
1. Fixed
2. Fixed
3. Could not repro
4. Could not repro

In the case of both 3 and 4, the function has been modified since the bug was submitted to return only the names of the individual items and _not_ to prepend the given path. So the results for 3 are the child folders and the results for 4 the child files, as expected.

**Comment by danadrew** [comment]
Some change in integration branch seems to have fixed bugs 3 & 4. They still happen in master, but should be fixed as soon as integration is merged in.
