### ISSUE TITLE
Add better support for Asian languages in TextBox.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#376]
With Asian languages that use characters for words, they don't separate words with spaces. Currently the designer relies on spaces to determine word wrapping, and this is making these Asian languages look strange. Add in an option that can be specified when setting up a MOAITextBox to tell the designer that an Asian language is being used and that it is safe to wrap between characters.

**Comment by patrickmeehan** [comment]
This is done. Added setWordBreak () to MOAITextBox. Use WORD_BREAK_NONE for default behavior (words are not broken) and WORD_BREAK_CHAR to treat every character as a word.

Need to test for regressions as I've been mucking about in the layout code. Also need to extend this mechanism to support custom breaking schemes (such as hyphenation) via a Lua callback.
