### ISSUE TITLE
Bug when rotating a text box about the x- or y-axes.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#377]
See sample on master branch: samples / test / textbox-rotation

There are two problems when you rotate about either the x- or y-axes (z-axis is fine):
1. The edges of the text box appear to just move inward and cut off text. The text itself does not appear to rotate at all.
2. The text box doesn't appear to rotate by the correct amount. In the sample I tell it to rotate by just 5 degrees about both the x- and y-axes and it appears to rotate much further than 5 degrees. If you try different values, it appears to rotate very quickly at low values and then slow down as it approaches 90 degrees.

**Comment by patrickmeehan** [comment]
OK, so turns out the problem was just that the camera didn't have good near/far plane settings for a 3D rotation. I modified the sample to use a perspective camera to show that the rotation is OK.
