### ISSUE TITLE
Filling an entire page of a text box with new lines will make nextPage not function.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#379]
See sample in master branch: samples / test / textbox-paging6

If you fill up an entire page of a text box with new lines and don't include any other characters, the new lines will appear in the wrong location on the page (shown by debug drawing) and nextPage () will also not work. Press space bar in the sample to call nextPage ().

**Comment by patrickmeehan** [comment]
OK, should be fixed now.
