### ISSUE TITLE
Reading from a file stream when there is nothing to read gives the wrong output

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#381]
See sample in integration branch: samples / test / empty-filestream-read

If the cursor is at the end of a file stream and you try to read from it, you will get unexpected results.

With read 8, 16, 32, U8, U16, U32, Float, or Double it will return nil properly but then give you a number of bytes instead of 0.

With readFormat, it will return a value of -52 every time and then say 0 bytes were returned.

In every case they should return nil and 0 bytes.

**Comment by patrickmeehan** [comment]
OK, should be fixed now.
