### ISSUE TITLE
Crash when loading a texture in integration branch

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#388]
See anim-basic sample.

I have narrowed it down to the following line that is crashing:
gfxQuad = MOAIGfxQuad2D.new ()
gfxQuad:setTexture ( "moai.png" )

This line crashes as well:
local texture = MOAITexture.new () 
texture:load ( "moai.png" )

**Comment by adamvillalobos** [comment]
I'm an idiot... https://github.com/moai/moai-dev/commit/69e6588
