### ISSUE TITLE
getRelativePath doesn't always return a relative path

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#390]
See sample in integration branch: samples / test / filesystem-getrelativepath

In the sample I get the absolute path to a folder and then call getRelativePath and it gives me back a ./ prepended to the full absolute path. The relative path should be much shorter.

**Comment by patrickmeehan** [comment]
Should be fixed now.

**Comment by danadrew** [comment]
I updated the same sample to show another issue. It appears to only subtract the working directory without shortening the remainder if it has a .. in it. In the sample, it returns 'test/../test/' and it should just return 'test/'

**Comment by patrickmeehan** [comment]
Turns out my fix for issue #391 also fixed this follow-on issue...
