### ISSUE TITLE
Directory paths not shortened with a .. without a trailing /

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#391]
See sample in integration branch: samples / test / filesystem-path-not-shortened

If you call setWorkingDirectory or getAbsoluteDirectoryPath with a path that includes a .. but doesn't have a / at the end, then the path will not be shortened properly, ie. you can get a path that looks like this:

C:/Users/Dana/Documents/GIT-Repositories/moai-dev-integration/samples/test/filesystem-path-not-shortened/../

**Comment by patrickmeehan** [comment]
The fix will only handle the case where there's a missing '..'. Bigger question is what to do and how to report/log errors for malformed paths and/or filenames.

**Comment by danadrew** [comment]
Resurrecting this issue because it appears to have regressed. The code that was added to resolve this issue was deleted in commit bff227fac863713731daa53a29af99b3c7ec3f58. I didn't want to add it back in myself because I don't know the reason for its deletion.

**Comment by danadrew** [comment]
This is fixed.
