### ISSUE TITLE
ZipFS deflate is corrupting the data

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#392]
See sample in integration branch: samples / test / zipfs-deflate

If you deflate data and immediately inflate it, you don't get back what you started with. In the sample I use an image file and the image that is inflated is corrupted. It seems to be an issue with the deflate function, because it appears that the inflate function is complaining about the data already being corrupted.

The sample should create an image 'moai2.png' which is a copy of 'moai.png'.

**Comment by patrickmeehan** [comment]
This appears to be fixed.

Also, FWIW - nothing to do with zipfs. This was just a bug in the implementation of USDeflateReader. ZipFS is (was) specifically the virtual file system.
