### ISSUE TITLE
On-screen keyboard lags and freezes on ipad

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#398]
Use the sample: samples/ios/app-keyboard

When using an ipad with iOS 5.0, the keyboard will lag and freeze if you use the standard split gesture to split and unsplit the keyboard repeatedly. It happens frequently after around 3-5 splits, it will start to have noticeable lag at first and then it will completely freeze.

I tested the on-screen keyboard on the facebook app and it doesn't lag or freeze when I split, so it seems to be an issue with moai.

**Comment by patrickmeehan** [comment]
This can wait until next release. Not super urgent.

**Comment by patrickmeehan** [comment]
trello
