### ISSUE TITLE
main.lua doesn't execute on ios in the integration branch

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#399]
You can use any sample on ios and you should see this, I used samples/ios/app-keyboard

In the integration branch only, scripts will not run on ios. The scripts are loaded into the lua file correctly, but then when trying to run they think that the file doesn't exist. This is because the return value from GetAbsoluteFilePath () is missing a / near the end. It is looking for the file "/var/mobile/Applications/F775F453-8CF2-497C-8D46-953AA0E3D75B/MoaiSample.app/luamain.lua" and the end should say "lua/main.lua". It looks like the working path was changed to not include a trailing / anymore.

**Comment by patrickmeehan** [comment]
Could you roll back and find out which checkin/lines of code broke this? The working path _should_ have a trailing slash, but if it doesn't it is probably due to something else getting 'fixed.' Would like to know what I was trying to fix so I don't re-break it.

**Comment by danadrew** [comment]
It was first broken in c195d0ea054490489ca8f22b4f2fff411b8ded1b

**Comment by patrickmeehan** [comment]
OK, that was my change... no idea why it showed as Adam's commit. Maybe due to a merge?

Anyway, I may have fixed this. Don't want to restart under OSX right now. When you have a second, try it out and send back to me if not fixed.

**Comment by danadrew** [comment]
Still seems to be broken.

**Comment by patrickmeehan** [comment]
trello

**Comment by adamvillalobos** [comment]
Re-opening since it doesn't seem to be fixed...

**Comment by adamvillalobos** [comment]
uhh wrong one.
