### ISSUE TITLE
Loading an image from a databuffer is failing

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#405]
See sample in integration: samples/test/load-texture-from-buffer
Note: the first commit where this was broken was cc11a45d53abf50bb2852f8aa5bde5b0d7983fa1

The sample should show Adam's facebook pic in the window. It seems to be failing to load the texture from the databuffer, printing out the width and height after loading it says it is 0x0.

**Comment by patrickmeehan** [comment]
The sample currently in 'integration' doesn't look like it has anything to do with this bug. Did you check in the correct version?

**Comment by patrickmeehan** [comment]
OK, I updated the sample and fixed the bug.
