### ISSUE TITLE
MOAISerializer can't handle unescaped quotes

### ISSUE THREAD

**Issue by jlytledistinctdev** [moai/moai-dev#409]
So I was serialized some json encoded data to a file, and I discovered that I couldn't parse the file back in once I had done this. Turns out, it gets dumped raw, quotes and all, which means its now not valid Lua anymore. I am currently working around the issue by escaping my quotes on the way into the serializer, but that's kinda a pain so it'd be nice if it did that for me.

**Comment by jlytledistinctdev** [comment]
Here's the code for a fixed version of the function _escapeString in MOAISerializer:

//----------------------------------------------------------------//
static STLString _escapeString ( cc8\* str ) {

```
u32 len = ( u32 )strlen ( str );

STLString outStr;
outStr.reserve ( len * 2 );

for ( u32 i = 0; i < len; ++i ) {
    char c = str [ i ];
    if ( c == '\\' ) {
        outStr.append ( "\\\\" );
    }
    else if ( c == '"' ) {
        outStr.append ( "\\\"" );
    }
    else {
        outStr.push_back ( c );
    }
}
return outStr;
```

}

**Comment by patrickmeehan** [comment]
It's in! Finally!

Thank you! :)
