### ISSUE TITLE
path in .fnt files are treated as absolute.

### ISSUE THREAD

**Issue by pygy** [moai/moai-dev#426]
If you move the fnt file and the corresponding png file, the letters become black boxes.

It turns out that the path referenced in the .fnt file ("CopperPlateGothic.png") is absolute. the .png must be in the current working directory, regardless of the location of the .fnt.

see sample/font/bmfont

**Comment by patrickmeehan** [comment]
I guess I need a repro of this. Looked at the code... the standard path for initializing a texture from a filename is followed. So the texture filename is relative to the .fnt file and is expanded to absolute when the .fnt is loaded... so it should be OK for the current working directory to change.

Will close this until I see a repro case.

**Comment by patrickmeehan** [comment]
Ah, I got it. Sorry, misunderstood.

**Comment by patrickmeehan** [comment]
Fixed! Huzzah!
