### ISSUE TITLE
Samples / texture/PVR: No output

### ISSUE THREAD

**Issue by pygy** [moai/moai-dev#429]
This may be an hardware issue on my side, but I don't get any output from this sample. Black window, and that's all.

**Comment by patrickmeehan** [comment]
What hardware are you testing on?

**Comment by eedelman** [comment]
I am seeing output just fine on an iPhone 4. Let me know what device you have issues with. I should note that PVR is an iOS only feature as well.

**Comment by pygy** [comment]
It was on my 2006 MacBook Pro. I didn't know it was iOS only.
