### ISSUE TITLE
Integration branch: USMD5Writer.cpp missing

### ISSUE THREAD

**Issue by pygy** [moai/moai-dev#440]
I get this:

```
moai-dev/xcode/libmoai/../../src/uslscore/USMD5Writer.cpp: No such file or directory
```

I suppose that it should look for USHashWriterMD5.cpp instead, but I don't know how to update the build script.

**Comment by ziplinebuild** [comment]
Thats odd, it should be there....

On Tue, Jul 31, 2012 at 4:05 PM, pygy <
reply@reply.github.com

**Comment by pygy** [comment]
The only files in uslscore containing "MD5" are USHashWriterMD5.h and USHashWriterMD5.cpp...

I'm building a fresh git clone.

It isn't present in the github repo either.

https://raw.github.com/moai/moai-dev/integration/xcode/libmoai/libmoai.xcodeproj/project.pbxproj mentions it, but not HashWriter*.

**Comment by adamvillalobos** [comment]
This is fixed.
