### ISSUE TITLE
3d picking bug

### ISSUE THREAD

**Issue by glenwong** [moai/moai-dev#448]
I've run into some weird issues with propListForRay, synced to the latest moai-dev on master.

I took the 3d input test and rewrote it to use MOAIGfxQuad2D's instead of meshes and the ordering isn't correct:

The problem appears when you click in the area where the two props being drawn overlap. You would expect the prop on the right to get precedence because it is closer to the camera (it's also being drawn on top), except what actually happens is that the one behind is chosen. I've tried a few sort modes and that doesn't seem make a difference.

**Comment by adamvillalobos** [comment]
https://github.com/moai/moai-dev/commit/33f43768092851b1a9842149011d5cc7134ad64c
