### ISSUE TITLE
MOAICpBody doesn't register MOAITransformBase functions for lua

### ISSUE THREAD

**Issue by DaanBroekhof** [moai/moai-dev#449]
According to the Lua docs, MOAICpBody extends MOAITransformBase, but when attemping to call 'getWorldRot()' on an MOAICpBody in lau, it fails with `attempt to call method 'getWorldRot' (a nil value)`.

The call to MOAITransformBase::RegisterLuaFuncs is missing in MOAICpBody.cpp:

``` c++
//----------------------------------------------------------------//
void MOAICpBody::RegisterLuaFuncs ( MOAILuaState& state ) {

    MOAITransformBase::RegisterLuaFuncs ( state ); // Add this line

    luaL_Reg regTable [] = {
```

**Comment by patrickmeehan** [comment]
Thanks! Got it :)
