### ISSUE TITLE
MOAIProp2D:setVisible(false) doesn't work with setParent()

### ISSUE THREAD

**Issue by sakim** [moai/moai-dev#450]
MOAIProp2D:setVisible(false) doesn't work with parent.

Even if a prop has a parent, its visibility should be changed.

I'm working on master branch.

**Comment by sakim** [comment]
Please add isVisible() method when you fix this issue.

**Comment by eedelman** [comment]
If you are using the _setParent function on the prop, you should know that it is merely a convenience function that sets attribute links for Color, Transform and Visibility. After using this function, you can remove any of these links or add more. I would recommend setting up functions on the Lua side to control your parenting, as you will have more control and can implement the logic to handle your issue there.
