### ISSUE TITLE
MOAIParticlePexPlugin issues

### ISSUE THREAD

**Issue by glenwong** [moai/moai-dev#453]
As referenced in this post: http://getmoai.com/forums/post5618.html

The sample should include the use of forceUpdate() or at least reference it, as moving a particle effect around is quite a common use case.

**Comment by glenwong** [comment]
Actually after further testing the situation is even worse. If your emitter is parented to other props you need to go up the chain and call forceUpdate() in order fo the emitter to be positioned properly.

**Comment by patrickmeehan** [comment]
Should work now...
