### ISSUE TITLE
android / app-backbutton sample

### ISSUE THREAD

**Issue by meapps** [moai/moai-dev#457]
cant get the sample and code running.

Error message: hello, Android!
...ons/moai-sdk/samples/android/app-backbutton/main.lua:17: attempt to index global 'MOAIApp' (a nil value)
stack traceback:
...ons/moai-sdk/samples/android/app-backbutton/main.lua:17 in main chunk

**Comment by eedelman** [comment]
Everything seems to be in working order here. Tested on Samsung Nexus S, 4.0.4
