### ISSUE TITLE
MOAIPathFinder does not use a*

### ISSUE THREAD

**Issue by jrabek** [moai/moai-dev#594]
For the same computational/memory overhead, MOAIPathFinder can be using a\* and finding much better paths than the current implementation.

The current implementation only uses the heuristic to the target and does not add in the cost of the path traveled so far resulting in circuitous paths in some cases.

I have implemented a\* on the following branch:
https://github.com/jrabek/moai-dev/tree/a-star

I wasn't sure if this was intentional so I am filing this as a bug instead of a pull-request.

Let me know if I should just open a pull request instead.

Also, in the same branch I pushed a separate commit that will path find for rectangular entities larger than one grid square (bosses, groups, etc)

**Comment by jrabek** [comment]
https://github.com/jrabek/moai-dev/commit/9197ad6b2a17d57e986bed7582ba240e5493c7fb

**Comment by adamvillalobos** [comment]
Thanks, we'll take a look at this.

**Comment by DanielSWolf** [comment]
I believe this issue can be closed. @superquadratic implemented A\* pathfinding in issue #770, which has been merged.

**Comment by makotok** [comment]
Thank you for information. Close.
