### ISSUE TITLE
Re-implement optimized special case view culling for 2D

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#6]
With the move to 3D we now use a view volume for culling, even when rendering 2D or mostly 2D scenes. This obviously is a lot less efficient. We should look into falling back on a simpler culling scheme using 2D rectangles in certain situations. This could be done automatically or as an extra setting on MOAILayer or MOAIPartition.

**Comment by adamvillalobos** [comment]
Closing since this is already implemented, the rest of this task is part of issue #142
