### ISSUE TITLE
How to create ObjectPool, Pause & Resume Game, and Capture GroupLayer ?

### ISSUE THREAD

**Issue by haipq7641** [moai/moai-dev#600]
With corona is easy !
with rapanui?

P/s: 
groupLayer:saveImage("captureLayer.png")

and

sceneGame:pause()
sceneGame:resume()

if Moai and Rapanui there that I do not know, please show me?

**Comment by patrickmeehan** [comment]
Hi, KaKaVip:

You can post questions/requests in the getmoai.com forums. Also, RapaNui is a 3rd party contribution - we (Zipline) don't maintain/support it.

Good luck!
