### ISSUE TITLE
Pixel unpack alignment is not set

### ISSUE THREAD

**Issue by kodemeister** [moai/moai-dev#601]
Currently Moai doesn't make use of glPixelStorei. Because of this some of my NPOT textures look distorted.

I've used the following code to get them working:
`glPixelStorei(GL_UNPACK_ALIGNMENT, 1);`

Also I found 'load-jpg' sample in the source tree specifically demonstrating the texture distortion issue. Is this the intended behavior or just a bug?

**Comment by quocble** [comment]
I'm experience the same issue.  Thank you for pointing out the fix.

Added your change on MOAITextureBase.cpp:174

**Comment by makotok** [comment]
Fixed.
To close.
