### ISSUE TITLE
Nacl and MOAIEnvironment

### ISSUE THREAD

**Issue by bartoleo** [moai/moai-dev#603]
running Moai in Nacl Host there are no informations about Nacl
the only one information is MOAIEnvironment.osBrand = "Linux"
here my output:
               Display Name :   nil
                     App ID :   nil
                App Version :   nil
            Cache Directory :   nil
   Carrier ISO Country Code :   nil
Carrier Mobile Country Code :   nil
Carrier Mobile Network Code :   nil
               Carrier Name :   nil
            Connection Type :   nil
               Country Code :   nil
                    CPU ABI :   nil
               Device Brand :   nil
                Device Name :   nil
        Device Manufacturer :   nil
                Device Mode :   nil
            Device Platform :   nil
             Device Product :   nil
         Document Directory :   nil
         iOS Retina Display :   nil
              Language Code :   nil
                   OS Brand :   Linux
                 OS Version :   nil
         Resource Directory :   nil
                 Screen DPI :   nil
              Screen Height :   nil
               Screen Width :   nil
                       UDID :   nil

**Comment by makotok** [comment]
NaCL is no longer supported. Close.
