### ISSUE TITLE
prop:getLoc sometimes returning NaN

### ISSUE THREAD

**Issue by lattejed** [moai/moai-dev#606]
I'm seeing prop:getLoc () sometimes return NaN if the prop's location is being animated.

The situation occurs while the prop is being animated with setLoc () inside a timer loop. Upon user interaction the timer loop is cancelled, the location is checked and a new timer loop is started.

**Comment by makotok** [comment]
Very mysterious phenomenon. It still occur?

**Comment by lattejed** [comment]
Haven't used Moai in year. No idea really.
