### ISSUE TITLE
MOAIEnvironment.screenWidth returns nil on (Android) Sony Xperia P

### ISSUE THREAD

**Issue by asyncx** [moai/moai-dev#626]
As the title says, MOAIEnvironment.screenWidth seems to return nil on my Sony Xperia P running Android 4.0.4

The game APK was compiled against Android SDK 17 (4.2). Would there be any other information I can provide? :)

**Comment by catwell** [comment]
You have probably fixed this by now, but the reason probably was that these properties [don't exist anymore](https://github.com/moai/moai-dev/blob/bb5b117a780c32010be451104391e4960212b98d/docs/release-notes.txt#L98).

**Comment by makotok** [comment]
> MOAIEnvironment - screenWidth/screenHeight renamed to horizontal/verticalResolution

There is no problem as above.
To close.
