### ISSUE TITLE
Integrate Billing Revolution into the Android host

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#63]

**Comment by seanzipline** [comment]
A production account has been set up for you.  Access is available at:

https://services.billingrevolution.com/merchant/default.asp

Username:  zipline
Password:  zl123

Test Card
4111 1111 1111 1111
Exp Date 1212
CVV 123

A sample product has also been set up which should help expedite assessment/testing.  Let me know if you want to schedule a call for a quick walk through of the platform.

**Comment by patrickmeehan** [comment]
Not moving forward with this.
