### ISSUE TITLE
FMOD Update not called in iOS project setup

### ISSUE THREAD

**Issue by typeoneerror** [moai/moai-dev#633]
We've switched to FMOD as we were never able to get seamless background loops to work with UNTZ. One thing I noticed about your sample iOS setup, is that it never seems to call AKUFmodExUpdate () and therefore, sounds eventually stop playing on device. Was wondering where the best place to put this is? Currently, we've added it just after AKUUpdate() in onUpdateAnim.

``` objective-c
    -( void ) onUpdateAnim {

        [ self openContext ];

        AKUSetContext ( mAku );
        AKUUpdate ();

#ifdef USE_FMOD_EX

        AKUFmodExUpdate();

#endif

        [ self drawView ];

        //sometimes the input handler will get 'locked out' by the render, this will allow it to run
        [ self performSelector: @selector(dummyFunc) withObject:self afterDelay: 0 ];
    }
```

**Comment by frantufro** [comment]
Did this work for you? Please send us a pull request if it did!
Cheers!

**Comment by frantufro** [comment]
Closing this since it's already merged.
