### ISSUE TITLE
MoaiView.mm can't compile - broken AKUSetDefaultFrameBuffer function reference

### ISSUE THREAD

**Issue by Nepherhotep** [moai/moai-dev#655]
AKUSetDefaultFrameBuffer function was removed in commit 428c4a5c19eab136aae5ba109d834db6d026167e, but MoaiView.mm still contains obsolete  AKUSetDefaultFrameBuffer function call (line 206). After removing that line the code can be compiled, but application screen in that case is empty.

**Comment by frantufro** [comment]
I'll be working on that this week. If you manage to solve it before I fix it, please send a pull request.

**Comment by frantufro** [comment]
This has been addressed.
