### ISSUE TITLE
start using semantic versioning for new versions

### ISSUE THREAD

**Issue by dorongutman** [moai/moai-dev#680]
Semantic versioning (http://semver.org/) is a set of rules for naming a version. Basically, it means versions look like 1.2.3, with optional pre-release tags (1.2.3-beta1) or build information (1.2.3+build.11).
It is a growing concept being used in more projects every day.

I am not connected in any way to the development of semver, but I do use it for my own purposes.

**Comment by halfnelson** [comment]
Looks like this was adopted. Thanks
