### ISSUE TITLE
Messed up box2d polygon

### ISSUE THREAD

**Issue by vertti** [moai/moai-dev#681]
If I create a polygon for a physics body with:

```
body:addPolygon{139,36,203,39,198,-28,135,-25,138,28}
```

I get a "hand-drawn rectangle" like I expected. But instead if I use

```
body:addPolygon{[1]=139,[2]=36,[3]=203,[4]=39,[5]=198,[6]=-28,[7]=135,[8]=-25,[9]=138,[10]=28}
```

which is exactly the same table, I get a completely messed up polygon.

So I'm guessing moai is not using the indexes correctly but instead some iterator?

Yes, it's a serialization tool I use, and yes I can rebuild the table but it should not be needed, this is definitely a bug in MOAI.

**Comment by seclorum** [comment]
First example is a table-as-Array.  Second is table-as-Hash.  There is actually a difference.  Its not exactly the same table and won't be iterated the same way.

See http://www.lua.org/gems/sample.pdf Page 19

**Comment by vertti** [comment]
I know the difference but when there's indexes available, MOAI should iterate through them and not by hash order.

**Comment by makotok** [comment]
I think this is a specification. Close so old.
