### ISSUE TITLE
MOAITextBox does not work

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#699]
If built the master of the latest, MOAITextBox does not work.
Master branch still does not work?

```
Last login: Tue May 14 03:08:08 on ttys000
makoto-air:~ mkinoshita$ /Users/mkinoshita/moai-sdk/samples/textbox/textBox-alignment/run.sh ; exit;
main.lua:21: attempt to call method 'loadFromTTF' (a nil value)
stack traceback:
    [C] in function 'loadFromTTF'
    main.lua:21 in main chunk
```

**Comment by jeiting** [comment]
I think you want to call load() not loadFromTTF(). MOAITextBox should automatically load a TTF.

**Comment by makotok** [comment]
Process is abnormally terminated by memory access is another sample.

This problem is because MOAIFreeTypeFontReader is not registered.
It works fine if you add the following code.
I pull request later.

``` C
REGISTER_LUA_CLASS ( MOAIFreeTypeFontReader )
```
