### ISSUE TITLE
SDK doc still lists moveLoc, moveRot as taking 2D args, rather than 3D

### ISSUE THREAD

**Issue by bpeck** [moai/moai-dev#708]
SDK documentation listed here:
http://getmoai.com/docs/class_m_o_a_i_transform2_d.html#acd24bff873fba8b018038ce04c9f5f88

Lists the move\* methods as only taking an X and Y argument, but does not mention that a Z argument must also be supplied.

See https://github.com/moai/moai-dev/issues/402 where is was concluded that the 2D wrappers for these functions would be deprecated.

**Comment by halfnelson** [comment]
fixed. Thanks.
