### ISSUE TITLE
MOAITextBox leaks texture memory

### ISSUE THREAD

**Issue by Kaali** [moai/moai-dev#718]
Fonts leak a bit of texture memory, which cannot be retained in any way. By reapplying Tommo Zhou's commit 9c19a992b5ca76c0ecbe8d47e54de255dde6e315 the problem goes away. But that patch was reverted by 7605c75a707a75ae192660dafbdfb644c20b5f90

**Comment by halfnelson** [comment]
tommo Zhou's fix broke fonts on android after a resume, stopping the font from being recreated by preventing it ever getting invalidated.
https://github.com/moai/moai-dev/issues/838

**Comment by tommo** [comment]
I didn't know that since I only work on iOS and desktop.
Good to know what's the issue.

**Comment by makotok** [comment]
This problem still occurs?

**Comment by Kaali** [comment]
I'm not part of the project anymore where Moai was used, so I cannot confirm this issue anymore.

**Comment by halfnelson** [comment]
I think the fix from #838 took most things into account. Nobody is reporting any leaks

**Comment by makotok** [comment]
Thank you for information. Close.
