### ISSUE TITLE
Linux build scripts and sample host

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#73]

**Comment by seanzipline** [comment]
We seem to have lost the cmake structures used to build Moai on Linux -- they're present in bjorn/moai-beta/, but the source tree (esp. src/aku) appears to have changed too much to make it easy for a newcomer (I did try!) to bring 'em up to date. Is this something we're likely to get back in the near future, or should I write off the ability to run my Moai projects under Linux? Or is there something I'm missing...?

**Comment by patrickmeehan** [comment]
https://github.com/moai/moai-beta/issues/14

Yeah, should tackle this as soon as we've made some headway on the build server.

**Comment by patrickmeehan** [comment]
trello
