### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Vavius** [moai/moai-dev#751]
Looks like this commit https://github.com/moai/moai-dev/commit/1a858c7be856d7fd8c440ec7290adcf1af8e7da8 causing mass memory leaks. Any MOAINode that have attributes linked to another node seems never be collected. 
I have tested on flower library samples and my projects with two Moai builds: most recent one and most recent with this change reverted: 

```
if ( refCount == 1 ) {
    this->mUserdata.MakeStrong ();
}
```

Histogram shows allocations continuously growing after each scene switch, while reverting that commit returns things to normal as it was before.

**Comment by superquadratic** [comment]
Funny, I'm having a hard time trying to understand this just now. In my project, the symptoms are the same, lots of unreleased Moai objects that were garbage-collected before.

@patrickmeehan, could you please elaborate on the garbage collection issue this code is supposed to fix?

**Comment by superquadratic** [comment]
@Vavius, are you also using flower in your projects? The issue might be specific to the library then, and we'd have to look into flower to see if it creates circular references somewhere.

**Comment by Vavius** [comment]
@superquadratic, yes, I do use flower in my projects. 
And yes, flower creates circular references. But circular references should be resolved by lua gc, and they were until this change. I've commented those 3 lines out and all Moai objects were collected as before.

**Comment by makotok** [comment]
This would bug.
I memory leak regardless of the flower.

Strong reference is not GC.
For example, a reference MOAIPartition of MOAILayer is strong.
To GC, it is necessary to set the MOAIPartition another.

**Comment by makotok** [comment]
I sent a pull request to correct it.
#761

**Comment by patrickmeehan** [comment]
The intent is to set a strong ref only when the engine needs to hang on to an object even if it is out of scope. If the engine ref counts an object then it gets made strong. If the engine ref count is 0, then the ref is weak and Lua's GC can resolve the circular reference.

The change @makotok commented out was introduced because Lua was garbage collecting objects while they were still in use by the engine. I tested it against my own circular ref sample, but if there's another circular ref introduced by attribute linking I will look into it.

Seems that neither fix (makotok's and mine) is correct. My fix introduced a bunch of leaks. makotok's fix reintroduced the crash I was trying to get rid of.

It's 3am here now... will look into this tomorrow.

**Comment by makotok** [comment]
@patrickmeehan 
Thank you for answers.
For now, I did not crash by GC.
Do you have a sample for generating the problem?

**Comment by bullno1** [comment]
One way is to carefully examine C++ code and choose strong/weak reference carefully.

Another way is to tap into Lua's GC and has it manage everything. In this post, I outlined a way to let Lua trace the internal of a Moai object:
http://getmoai.com/forums/post11390.html#p11390

It may incur some performance penalty as an extra table lookup is required for every method invocation.

**Comment by patrickmeehan** [comment]
@bullno1 - I'm thinking there must be an extra ref count in the engine somewhere. Am going to go through it all again. Also not completely sure I need the make strong on ref count > 1. I didn't do it at first (in spite of adding the virtual methods to support it), so must have originally convinced myself it wasn't needed. Thx for the post about Lua trace as well - looks interesting!

@makotok - I noticed a crash during a piece of code where a bunch of objects were being churned through. Some of them were getting garbage collected before the engine finished with them. If I don't find a clear answer in the code I will try to re-create the crash.

**Comment by patrickmeehan** [comment]
OK, so I was mistaken to add the strong ref to OnRetain. After reading the code and thinking about the problem I remembered the reasoning and commented accordingly. But I think there's still some unsafe stuff going on. Here's my pull request and some discussion:

https://github.com/moai/moai-dev/pull/769

**Comment by makotok** [comment]
This problem has been fixed. 
Close.
