### ISSUE TITLE
Delete unnecessary branch

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#759]
Currently, unwanted branches there are many.
Have caused the lower the productivity.
I delete a branch that has not been updated for a long time.

**Comment by makotok** [comment]
I have removed unnecessary branch.
I do not know the branch remaining.

(1) Necessary
- development
- master
- publish
- staging
- studio

(2) Unknown
- cmake-project
- flascc
- hotfix
- linux
- lua-classes
- stable
- tango

**Comment by CircuitCipher** [comment]
Stable and hotfix are necessary. Read the continuous integration page on the wiki.
https://github.com/moai/moai-dev/wiki/Ci-server-and-release-process-requirements

**Comment by makotok** [comment]
statable branch is not currently stable.
what master branch should be stable.

I think the person who statable branch does not exist is good.
If necessary, they should be considered operational.

**Comment by CircuitCipher** [comment]
They have different purposes.  One triggers a build on the CI, the other doesn't.  Not sure if they still want that functionality.

You may want to consult @patrickmeehan  about master vs stable.

**Comment by CircuitCipher** [comment]
On second thought, I see that they only have master because it's the default branch.  I think I agree.  We should consolidate stable into master and master should be for stable code.

**Comment by makotok** [comment]
I see the situation for a while.
I listen to talk to Patrick.

We saw where the master branch is broken many times.
I do not want to see the future such situations.

**Comment by patrickmeehan** [comment]
Looks like there are many more branches missing - collision, skeletal, overlap to name a few. These branches represent a lot of engineering time for me, even if I have not finished and merged them into the release.

Guys, I need these branches back. I am on a new computer and can't seem to get to them anymore. Did not realize when I added you to the team that you would take a hatchet to my work. In the future, if you didn't create a branch, don't delete it.

@makotok - Restore anything you have deleted. I will go through these and clean them up when I have time.

**Comment by makotok** [comment]
Sorry.
I have deleted the branch also inadvertently.

I look for the Fork repository.
I can see some
And I to restore.

https://github.com/theGoodEvil/moai-dev/tree/skeletal
https://github.com/theGoodEvil/moai-dev/tree/overlap

**Comment by makotok** [comment]
Branch which I have deleted as follows.
Result of referring to the fork, some still visible.
Will be able to restore.

makotok deleted branch playnomi at moai/moai-dev 2 days ago
makotok deleted branch payments_v3 at moai/moai-dev 2 days ago
makotok deleted branch ios_3rdparty_reorg at moai/moai-dev 2 days ago
makotok deleted branch lua_alt at moai/moai-dev 2 days ago
makotok deleted branch overlap at moai/moai-dev 2 days ago
makotok deleted branch zl_lua at moai/moai-dev 2 days ago
makotok deleted branch random-sfmt at moai/moai-dev 2 days ago
makotok deleted branch feature/android_keyboard at moai/moai-dev 2 days ago
makotok deleted branch feature/android_activityFinish at moai/moai-dev 2 days ago
makotok deleted branch asynch_texture_loading at moai/moai-dev 2 days ago
makotok deleted branch Testing at moai/moai-dev 2 days ago
makotok deleted branch adam_test at moai/moai-dev 2 days ago
makotok deleted branch three-dee at moai/moai-dev 2 days ago
makotok deleted branch skeletal at moai/moai-dev 2 days ago
makotok deleted branch pickingBugs at moai/moai-dev 2 days ago
makotok deleted branch nacl_wt at moai/moai-dev 2 days ago
makotok deleted branch nacl at moai/moai-dev 2 days ago
makotok deleted branch luasocket-test at moai/moai-dev 2 days ago
makotok deleted branch lineEndings at moai/moai-dev 2 days ago
makotok deleted branch lib_curl_update at moai/moai-dev 2 days ago
makotok deleted branch legacy at moai/moai-dev 2 days ago
makotok deleted branch klank-audio at moai/moai-dev 2 days ago
makotok deleted branch iso at moai/moai-dev 2 days ago
makotok deleted branch triangulation at moai/moai-dev 2 days ago

**Comment by patrickmeehan** [comment]
OK! This is good news. I will fork moai/moai-dev to patrickmeehan/moai-dev and pull those down once they are back. We can then re-delete them from moai/moai-dev. In the future I will work on patrickmeehan/moai-dev and send pull requests. That way we can just keep the 'official' branches for CI in moai/moai-dev, as you originally suggested.

Thank you for hopping on this so quickly, @makotok! :)

**Comment by patrickmeehan** [comment]
@makotok - Looks like I still have references to these in my remotes. I am restoring the ones I care about, so don't worry about it.

**Comment by makotok** [comment]
I'm sorry very much.
If I can do something if there is a request.

**Comment by patrickmeehan** [comment]
It's OK! I'm glad this happened. I think having my own fork for development is a better way to work. Your help is very valuable, so thank you!

I was able to pull all those branches over now. I am going to delete them again from moai-dev. Moving forward we can just keep those official branches for CI.

**Comment by makotok** [comment]
I careful the next time.
I would like to contribute in the future.
