### ISSUE TITLE
Attribute linking to box2d body slows the game to a crawl

### ISSUE THREAD

**Issue by vertti** [moai/moai-dev#781]
I have a shader that takes x and y coordinates with setAttrLink. If I link it to a prop and move the prop, everything runs fine, but I can't hook it to the prop's location when my prop is moved by a box2d body.

But if I do

```
shader:setAttrLink(1, physicsBody, MOAITransform.ATTR_X_LOC)
shader:setAttrLink(2, physicsBody, MOAITransform.ATTR_Y_LOC)
```

the game slows down to a crawl (and sometimes even crashes after a moment).

**Comment by halfnelson** [comment]
probably fixed by now, please reopen if still causing problems
