### ISSUE TITLE
Use GitHub/Jekyll/Gollum for SDK documentation

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#82]

**Comment by pygy** [comment]
Do you have a specific solution in mind?

**Comment by seanzipline** [comment]
Hey pygy. Just to be clear, this is a solution to replace our main documentation that currently exists on our wiki around getting started, building from source, etc. - it's not related to the class/method documentation that you've been helping to sort out. That said, we're looking at using a Github repository with HTML or wiki-like markup and using Jekyll or Gollum to process it for display on our site. It's inspired by this: http://www.engineyard.com/blog/2012/tao-of-documentation/

**Comment by seanzipline** [comment]
The advantage, BTW, among others is that it allows our Moai community to help write and improve our documentation. It's better than a wiki because it allows us to review documentation via pull requests and not have to manage wiki users, permissions, etc.

**Comment by pygy** [comment]
Edited, I hadn't read the Engine Yard post...

Gollum-site looks excellent. It would be even better if it were possible to send pull requests from the github wiki interface...

Regarding the user documentation, the current wall of link is IMO sub optimal. It is too big and makes it hard to find content. I only found http://getmoai.com/wiki/MoaiCloud through the comments in the hello world app on Moaicloud, for example.

**Comment by pygy** [comment]
I've send a feature request to get pull requests for Gollum pages.

**Comment by makotok** [comment]
Very old issue. Close.
