### ISSUE TITLE
GLUT vs SDL

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#830]
Currently, MOAI is support SDL and GLUT. 
Should continue in the future?

**Comment by ibisum** [comment]
> Currently, MOAI is support SDL and GLUT. 
> Should continue in the future?

My vote is to chuck GLUT and roll along with SDL.  Otherwise, why?

j.

**Comment by makotok** [comment]
I think the time being, I also host both and should be continued. 

Build at the same time, it should be a symbolic link to the moai?
(moai_glut,moai_sdl,--->moai)

**Comment by halfnelson** [comment]
why symbolic link to moai? both of them compile to moai.exe

**Comment by halfnelson** [comment]
zipline have abandoned the glut hosts (patricks latest merge said he was sick of glut). If we were to abandon one, then at least package it up as a custom host for people to keep using. Also the glut host is the only host that currently compiles down and runs the moai test suite, although the sdl host could probably me modified to do this too.

**Comment by makotok** [comment]
Used to leave this for the time being. Not abolished.
