### ISSUE TITLE
new changes break font rendering on android host

### ISSUE THREAD

**Issue by operat0r** [moai/moai-dev#838]
the huge changes between my contributions of the android camera support and the android keyboard support break the font rendering

detailed description of the problem http://getmoai.com/forums/new-changes-break-font-rendering-t2547/

nicer sample script http://pastebin.com/jjFCvDgp

**Comment by halfnelson** [comment]
https://github.com/moai/moai-dev/commit/fbadbaf52add5e8969fc93e1c2081732b3085eaa that is the only change I can see that would upset the font stuff. 

The only other thing we did was 
https://github.com/moai/moai-dev/commit/3bac82453d456e92aa4472310111b6288a0716cc
which is used by the glyph cache.

Maybe try reverting each change and seeing if that fixes it.

**Comment by halfnelson** [comment]
I can confirm that it was indeed one of those changes. I will let you know which one
