### ISSUE TITLE
build-android.sh broken on windows

### ISSUE THREAD

**Issue by Mattenklopper** [moai/moai-dev#839]
Trying to build MOAI 1.5 on windows for Android.

The script tries using visual studio which fails. Changing build-android.sh so it passes --windows to build.sh fixes this but spews out a cmake related error. 

Could not create named generator "MinGW

Haven't been able to get it past this step, don't have enough knowledge about the subject to make a good guess what could be going wrong.

**Comment by makotok** [comment]
You need to install MinGW.
However, I have not tried on Windows build-android.sh. 
I should be able to run as long as it is a method of the past.

./ant/make-host.bat

@halfnelson
Do you know a detailed way?

**Comment by Mattenklopper** [comment]
I do have MinGW installed, I'm using it to build moai 1.5 for windows, that's the weird thing. 

I will do some more experimenting with it when I get back at my main dev machine early next week.

**Comment by halfnelson** [comment]
https://github.com/moai/moai-dev/pull/852
should fix it. I added further instructions at https://github.com/moai/moai-dev/wiki/Building-for-android-on-windows

**Comment by Mattenklopper** [comment]
Yep the error is gone and it's building now, thanks!
