### ISSUE TITLE
Compatibility moai_lua.h

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#845]
The moai_lua.h, byte code of lua is defined. 
Is there a compatibility standard Lua and luaJIT? 
In addition, if the architecture of the CPU is different, it work?

https://github.com/moai/moai-dev/tree/master/src/lua-headers

**Comment by halfnelson** [comment]
From memory, moai_lua.h is just zipped up plain lua files. No luac involved. This was changed back when luajit was added.

**Comment by makotok** [comment]
Thank you for information. Closed so no problem.
