### ISSUE TITLE
Update docs for 1.5

### ISSUE THREAD

**Issue by halfnelson** [moai/moai-dev#846]
In order to help finish off 1.5 release, I have a gh-pages branch on moaiforge with the latest documentation built. http://moaiforge.github.io/moai-sdk/api/latest. I can't generate a pull request since moai-dev does not have the require gh-pages detached branch.

Is it possible to create the detached gh-pages branch as outlined by http://pages.github.com/  (click on "project site" button and "from scratch")

**Comment by makotok** [comment]
I can not in my account.
It is necessary to ask @patrickmeehan.

@patrickmeehan.
I want to create page do you accept?

**Comment by makotok** [comment]
I tried to copy the gh-pages. 
It worked?

**Comment by makotok** [comment]
https://github.com/moai/moai-dev/tree/gh-pages/api/latest

**Comment by halfnelson** [comment]
Yep you can see it at http://moai.github.io/moai-dev/api/latest/

https://github.com/moai/moai-dev/tree/gh-pages/api/latest

## 

Reply to this email directly or view it on
GitHubhttps://github.com/moai/moai-dev/issues/846#issuecomment-36772542
.
