### ISSUE TITLE
build-linux-sdl.sh: cmake doesn't check for OpenGL headers

### ISSUE THREAD

**Issue by theypsilon** [moai/moai-dev#848]
The consecuent error is hard to find. Check this gist: https://gist.githubusercontent.com/theypsilon/9314942/raw/3d6dd3395337483232276d0e87009c0fda330ea7/gistfile1.txt

I think would be convenient to handle this dependency with cmake. In this gist, the last output you get is misleading. You have to grep for 'fatal error' in order to find the problem which is maybe not trivial for many users.

**Comment by makotok** [comment]
Did this fix the problem? 
I can not confirm because I do not have a Linux environment.

**Comment by theypsilon** [comment]
The problem is not fixed, but is very very minor. Just makes the first build a little more annoying. I don't really understand cmake, so I can't take this, but it has to be very easy to add this check (if you know where).

Btw, you get the missing header by running "sudo apt-get install libglu1-mesa-dev" in debian systems.

**Comment by halfnelson** [comment]
The cmake script already forces a requirement on opengl. (find_package(opengl required). I am not sure how to make it forcibly include glu.h. I have a guide on compiling moai on ubuntu here: https://github.com/moaiforge/moai-sdk/wiki/Linux-build-(ubuntu-13.10)
maybe I can update the build instructions in the readme to reference that?

**Comment by halfnelson** [comment]
nm, i found some doco on the find_package(opengl) call. turns out it will not fail (even though required) if the glu isnt found, only if libgl is missing. But it does set a variable "OPENGL_GLU_FOUND    - system has GLU"
I should be able to check this in the build script and throw fatal error early
