### ISSUE TITLE
Binary only release of 1.5

### ISSUE THREAD

**Issue by halfnelson** [moai/moai-dev#861]
There have been calls for a binary release of 1.5 which just includes 
- moai binary for osx, linux and windows, 
- a prebuilt libmoai.so for android and host project
- a prebuilt libmoai.a with headers for ios and an xcode project
- a prebuilt moaijs.js file and html template. 
- prebuilt API docs
- Release Notes and ChangeLog
- samples with run scripts

Maybe look at the old distribute script

**Comment by makotok** [comment]
What to do to binary release? 
- It should be released on each platform? (Windows / OSX / Linux) 
- Create the necessary release shell. (release-win.bat, release-osx.sh, release-linux.sh)

**Comment by halfnelson** [comment]
got 1.7 out
