### ISSUE TITLE
Where does the iPhone sample set the callback openWindow()

### ISSUE THREAD

**Issue by caox** [moai/moai-dev#862]
I found MoaiSIM:openWindow() call the callback set in the following code snippet :

```
//----------------------------------------------------------------//
void AKUSetFunc_OpenWindow ( AKUOpenWindowFunc func ) {

    MOAISim::Get ().SetOpenWindowFunc ( func );
}
```

but I didn't find the code initialize the callback in the sample for iPhone. So, where did the initialization happen?

**Comment by makotok** [comment]
I suspect that there is no meaning in Android and iOS. 
Not Window.

**Comment by caox** [comment]
That means MoaiSIM:openWindow() actually  do nothing on iOS and Android?

Thanks for the reply.

在 2014年3月19日，上午1:00，makoto notifications@github.com 写道：
