### ISSUE TITLE
MOAIAppAndroid.BACK_BUTTON_PRESSED called multiple times

### ISSUE THREAD

**Issue by Mattenklopper** [moai/moai-dev#866]
When setting a listener for the back button, it gets called multiple times. There is currently no way to specify whether your callback should happen on ACTION_UP or ACTION_DOWN in lua. If you hold down the back button before releasing it your callback happens 3 times total. 

I think we should either allow the user to specify whether callback should happen on ACTION_UP/ACTION_DOWN or only execute Moai.backButtonPressed () on ACTION_UP if it is set.

Example:
Expected behavior: The background color should only change 1 time. It always changes 2 times and 3 times if you hold the button down.

Code:

``` lua
if MOAIEnvironment.horizontalResolution ~= nil and MOAIEnvironment.verticalResolution ~= nil then
    screenWidth = MOAIEnvironment.horizontalResolution
    screenHeight = MOAIEnvironment.verticalResolution
else
    screenWidth = 640
    screenHeight = 480
end

viewport = MOAIViewport.new ()
viewport:setSize(320, 240)
viewport:setScale(320, 240)

layer = MOAILayer2D.new ()
layer:setViewport ( viewport )
MOAISim.pushRenderPass ( layer )

MOAISim.openWindow ( "test", screenWidth, screenHeight )

math.randomseed(os.time())
timesPressed = 0

local frameBuffer = MOAIGfxDevice:getFrameBuffer()
frameBuffer:setClearColor(math.random(), math.random(), math.random(), 1) 
MOAIAppAndroid.setListener(MOAIAppAndroid.BACK_BUTTON_PRESSED, function()
    frameBuffer:setClearColor(math.random(), math.random(), math.random(), 1)
    timesPressed = timesPressed + 1
    print('Pressed back button '..timesPressed..' times.')
    return true 
end)
--Background color should only change 1 time when back button is pressed.
```

**Comment by halfnelson** [comment]
my recollection is that this was resolved in 1.6, thanks for the report!
