### ISSUE TITLE
MOAIHttpTask not exposed in LUA with Windows host

### ISSUE THREAD

**Issue by romainmoreau** [moai/moai-dev#881]
I tried building with MinGW with bin\build-win.bat with -DMOAI_CURL=TRUE.
I also tried generating projects with bin\create-projects-win.bat with -DMOAI_CURL=TRUE and building with VS 2013.
In both cases, I get this error on the LUA side when I try to use MOAIHttpTask : attempt to index global 'MOAIHttpTask' (a nil value))
Also, in both cases, I don't see in the build log a line about compiling MOAIHttpTaskCurl.cpp.

**Comment by halfnelson** [comment]
Nice find. The build-win.bat is missing a `-DMOAI_HTTP_CLIENT=TRUE` flag. Add this as well as ensuring that `-DMOAI_CURL=TRUE` and it should work. If this fixes it could you submit a pull with the changes. Thanks

**Comment by romainmoreau** [comment]
Thanks for the quick update, your fix works, I just submitted the pull request.

**Comment by makotok** [comment]
Merged.
