### ISSUE TITLE
getcwd in ZLVfsFileSystem failing sometimes

### ISSUE THREAD

**Issue by romainmoreau** [moai/moai-dev#894]
https://github.com/moai/moai-dev/blob/master/src/zl-vfs/ZLVfsFileSystem.cpp#L366 fails sometimes on Android when creating the main activity but it's pretty rare so hardly reproducible.
I'm unable to debug native code so I can't tell why the getcwd fails when it happens.

**Comment by makotok** [comment]
Thank you. Merged. Close.
