### ISSUE TITLE
API: have constructors accept a table for initialization?

### ISSUE THREAD

**Issue by pygy** [moai/moai-dev#90]
I find this:

```
local textbox = MOAITextBox.new {
    Font      = font, 
    TextSize  = font:getScale (),
    Rect      = { -160, -80, 160, 80 },
    Alignment = MOAITextBox.CENTER_JUSTIFY,
    YFlip     = true,
    String    = "You are dead!"
}
```

lighter than this:

```
local textbox = MOAITextBox.new ()
       :setFont      ( font )
       :setTextSize  ( font:getScale ())
       :setRect      ( -160, -80, 160, 80 )
       :setAlignment ( MOAITextBox.CENTER_JUSTIFY )
       :setYFlip     ( true )
       :setString    ( "You are dead!" )
```

a similar `object:setParam(tbl)` could share the implementation.

In the same vein, `one, two, three = object:getParams ("one","two","three")` would also be cool.

In both cases, the implementation may be hairy, though (Recursively call the parent constructors? How do you bind strings to methods in C++ without making a big switch statement?)

The biggest advantage of this strategy over method chaining is that you can recycle the parameter table (and change it a bit if needed).

**Edit**

Now that I think of it, a Lua implementation would be trivial.

```
function object:setParam(tbl)
    for k, v in pairs(tbl) do
        if type(v == "table") then
            self["set"..k](self,unpack(v))
        else
            self["set"..k](self,v)
        end
    end
    return self
end

function class.new(...)
    local tbl, obj = select(1,...)
    if type(tbl)=="table" then
        obj = class.realnew(unpack(tbl))
        obj:setParams(tbl)
    else
        obj = class.realnew(...)
    end
    return obj
end

function object:getParams(...) -- accepts a list of strings
    local args = {...}, -- lua 5.2 / LuaJIT compat
    for i = 1, #args do
        local res = {self["get"..args[i]](self)}
        if #res > 1 then args[i]=res -- if the getter has more than one result, return a table.
                    else args[i]=unpack(res ) 
        end
    end
    return unpack(args)
end
```

**Comment by patrickmeehan** [comment]
I'm thinking the Lua implementation is the way to go. We have other tasks for better integrating our Lua modules, wrappers and documentation with Moai. Will tag this for the backlog and review after 1.0...

**Comment by pygy** [comment]
I suppose that this will replace method chaining... Should I revert what I did in MOAIAction.cpp?

**Comment by patrickmeehan** [comment]
trello
