### ISSUE TITLE
iOS build script - fails after build on change dir

### ISSUE THREAD

**Issue by JDaance** [moai/moai-dev#907]
So this line fails for me: https://github.com/moai/moai-dev/blob/master/bin/build-ios.sh#L217

Basicly the script is in the `<root>/cmake/build` directory before line 217 and then tries to run `cd 'dirname $0'/..`. But that translates to `cd bin/..` in my os x terminal, and the script fails. Maybe we could replace it with `cd ../..` ? I'm not sure of the original intention here

**Comment by makotok** [comment]
I'm able to run. 
The code is independent of the current directory. 
Should work can be performed from anywhere. 

※ prefer to operate when being run from anywhere desirable shell. 

I have to start a shell with a double-click in OSX.

**Comment by makotok** [comment]
```
makoto-air:moai-dev mkinoshita$ pwd
/Users/mkinoshita/moai-dev
makoto-air:moai-dev mkinoshita$ echo `dirname ./bin/build-ios.sh`
./bin
makoto-air:moai-dev mkinoshita$ cd
makoto-air:~ mkinoshita$ pwd
/Users/mkinoshita
makoto-air:~ mkinoshita$ echo `dirname moai-dev/bin/build-ios.sh`
moai-dev/bin
makoto-air:~ mkinoshita$ 
```

**Comment by JDaance** [comment]
Yes that's the same result that I get. But before line 217 my script is in `moai-dev/cmake/build` and tries to run `cd 'dirname $0/..'` which is `cd bin/..` which means `moai-dev/cmake/build/bin/..` and then it fails.

**Comment by mohaalak** [comment]
I have the same issue building for ios .exactly at `cd 'dirname $0/..'`. do you solve it ? what it wants to do how to do it?

**Comment by JDaance** [comment]
I changed `cd 'dirname $0/..'` to `cd ../..`

:)

**Comment by mohaalak** [comment]
Thank you so much:D
