### ISSUE TITLE
ios-host, lua-headers-wrappers, are broken 

### ISSUE THREAD

**Issue by ezraanderson** [moai/moai-dev#919]
https://github.com/moai/moai-dev/blob/7b0de45d8904ede794d7665cf44746e83895eca7/src/host-ios/Classes/MoaiView.mm

execution order is incorrect, prevent moai.lua (headers) values to be correct

 AKUModulesRunLuaAPIWrapper (); --> should be bellow --> AKUIphoneInit ( application );

**Comment by halfnelson** [comment]
this has been merged. Thanks!
