### ISSUE TITLE
libcurl assestion error on windows with debug-builds

### ISSUE THREAD

**Issue by ezraanderson** [moai/moai-dev#922]
When building a debug-build with vs2010 there is a assertion error when using

task=MOAIHttpTask.new ( MOAIHttpTask.HTTP_GET )
task:performSync ()

This error does not happen or is suppressed when using a Release-build

MOAIHttpTaskCurl.cpp
curl_easy_perform ( this->mEasyHandle ); //CRASHING HERE

more information here
http://getmoai.com/forums/windows-httptask-exception-t2693/

**Comment by halfnelson** [comment]
built and ran with mingw64 fine.
built and ran with vs2012 fine (with some modules disabled)
built and ran on master of moai-dev with sdl_host true and luajit false, and runs fine.

**Comment by halfnelson** [comment]
luajit was using a different runtime dll. fixed in #924
