### ISSUE TITLE
ANDROID : moaidiag = nil

### ISSUE THREAD

**Issue by ezraanderson** [moai/moai-dev#925]
initialization order of "AKU" on android has a problem, moaidialog is nil

tested solution move -> AKUInit (); -> above -> AKUModulesContextInitialize ();

https://github.com/moai/moai-dev/blob/master/ant/host-source/source/project/src/moai/Moai.java

IOS had the same issue
https://github.com/moai/moai-dev/pull/920

**Comment by halfnelson** [comment]
Done
