### ISSUE TITLE
Code needs to be refactored to match current plug-in scheme

### ISSUE THREAD

**Issue by ezraanderson** [moai/moai-dev#929]
With the new plug-in & modules.

MOAISIm.cpp->update() ->
https://github.com/moai/moai-dev/blob/master/src/moai-sim/MOAISim.cpp
# if MOAI_WITH_HTTP_CLIENT && MOAI_WITH_LIBCURL

MOAIUrlMgrCurl::Get ().Process ();
# endif
# if MOAI_WITH_HTTP_CLIENT && MOAI_OS_NACL

MOAIUrlMgrNaCl::Get ().Process ();
# endif

Should be refactored and added to -> aaku_modules.cpp --> AKUModulesUpdate ()
# if MOAI_WITH_HTTP_CLIENT && MOAI_WITH_LIBCURL

AKUCurlUpdate()
# endif
# if MOAI_WITH_HTTP_CLIENT && MOAI_OS_NACL

AKUNaCiUpdate()
# endif

**Comment by halfnelson** [comment]
Done
