### ISSUE TITLE
Fix : build-ios.sh, xcodebuild needs arguments for release libraries.

### ISSUE THREAD

**Issue by ezraanderson** [moai/moai-dev#938]
xcodebuild needs arguments  passed in to make release optimized(-03)  libraries.
https://github.com/moai/moai-dev/blob/master/bin/build-ios.sh

easily makes C loops & logic twice as fast.

Example:
xcodebuild -target moai -sdk ${SDK} -arch ${ARCH} -configuration Release IPHONEOS_DEPLOYMENT_TARGET='6.1'

**Comment by halfnelson** [comment]
these scripts have been rewritten. Thanks
