### ISSUE TITLE
Update to openssl-1.0.0m or maybe openssl-1.0.1h

### ISSUE THREAD

**Issue by romainmoreau** [moai/moai-dev#940]
The following email received today explains the need :

> Hello,
> 
> One or more of your apps is running an outdated version of OpenSSL, which has multiple security vulnerabilities. You should update OpenSSL as soon as possible. For more information about the most recent security vulnerability in OpenSSL, please see http://www.openssl.org/news/secadv_20140605.txt.
> 
> Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered “dangerous products” and subject to removal from Google Play.
> 
> Regards,
> Google Play Team

**Comment by halfnelson** [comment]
i have begun updating to openssl-1.0.0m, just testing on each platform now and documenting any changes we have to make to get it to work
