### ISSUE TITLE
osx-i386 binarys on osx64

### ISSUE THREAD

**Issue by ezraanderson** [moai/moai-dev#946]
~
I struggled with getting 32bit binary to build via osx-64bit. I think there should be support for 32bit binary on Linux/Osx/windows via command line or flag.

---

Curl defines : 

https://github.com/moai/moai-dev/blob/master/3rdparty/curl-7.19.7/include-osx/curl/curlbuild.h   

```
     //LINE : 157
    //#define CURL_SIZEOF_LONG 8
    #define CURL_SIZEOF_LONG 4

    //LINE :184
    //#define CURL_SIZEOF_CURL_OFF_T 8
    #define CURL_SIZEOF_CURL_OFF_T 4
```

---

SDL -> needs force -m32--> line : 93

https://github.com/moai/moai-dev/blob/master/cmake/host-sdl/CMakeLists.txt

```
#LINE : 93
if (MOAI_LUAJIT)
   #set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pagezero_size 10000 -image_base 100000000 ")
 endif (MOAI_LUAJIT)
[/code] 
```

---

 Lua-jit -> LINE 57 ->   if (GCC_FORCE_32BIT) -> change to ->  if (GCC_FORCE_32_BIT)

https://github.com/moai/moai-dev/blob/master/cmake/third-party/luajit/CMakeLists.txt

build-osx-sdl.sh --> add --> DGCC_FORCE_32_BIT=TRUE \

https://github.com/moai/moai-dev/blob/master/bin/build-osx-sdl.sh

```
#add line: 40
-DGCC_FORCE_32_BIT=TRUE \
```

---

Forum Post: This is How I got it to build correctly for my custom builds.
http://getmoai.com/forums/osx-i386-binarys-via-osx64-t2732/

**Comment by halfnelson** [comment]
cmake build is mostly dead. Thanks for the reports.
