### ISSUE TITLE
MOAIImage segmentation fault when loading PNG

### ISSUE THREAD

**Issue by Zoomulator** [moai/moai-dev#949]
Running moai on arch linux with the sdl host. Converted the image to gif and that loads correctly, but the png image segfaults.

**Here's the backtrace from gdb:**

> # 0  0x00007ffff5df76e4 in memset () from /usr/lib/libc.so.6
> # 1  0x0000000000684b50 in MOAIImage::LoadPng(void_, void_, unsigned int) ()
> # 2  0x0000000000684f32 in MOAIImage::LoadPng(ZLStream&, unsigned int) ()
> # 3  0x000000000064cab3 in MOAIImage::Load(ZLStream&, unsigned int) ()
> # 4  0x000000000065157b in MOAIImage::_load(lua_State*) ()
> # 5  0x0000000000a8bd88 in lj_BC_FUNCC ()
> # 6  0x0000000000abc05a in lj_cf_package_require ()
> # 7  0x0000000000a8bd88 in lj_BC_FUNCC ()
> # 8  0x00000000006c48e0 in MOAILuaState::DebugCall(int, int) ()
> # 9  0x00000000006b86f4 in AKURunScript(char const*) ()
> # 10 0x0000000000570190 in SDLHost(int, char**) ()
> # 11 0x000000000056be69 in main ()

**Comment by halfnelson** [comment]
hrm, loading png files here fine. Could I get the branch you used to compile and the lua you used to load the png and the png file you tried to load so I can try and reproduce?

**Comment by Zoomulator** [comment]
Minimal code reproducing the error:

> local img = MOAIImage.new()
> img:load( 'trimtile.png' )

https://dl.dropboxusercontent.com/u/10564245/trimtile.png
Using a transparent background color, if that's worth noting.

Using moai/moai-dev master branch commit 1016b53e85f73094f2b5bef65b6a15f098429b9b

**Comment by Zoomulator** [comment]
Just noticed there's only support for PNG and JPG, so my test with a gif was pretty fruitless. =)
It says "Loads an image from a PNG" in the docs but I somehow missed it. Maybe good to generate an error in MOAIImage:Load if no supported format was found, since it just ignores the call silently as it is now?

Also worth noting is that MOAITexture loads the png file just fine and I'm able to display it.

**Comment by halfnelson** [comment]
Fixed by #953 which is now in the 1.5-development branch, and will be merged into 1.5-stable and master soon. Thanks for the informative bug report!

**Comment by Zoomulator** [comment]
Excellent! Thank you!
