### ISSUE TITLE
Performance hitch on Android

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#95]
http://getmoai.com/forums/new-users/sliding-background-issue/#p1793

Possible due to Java GC running.

**Comment by seanzipline** [comment]
I told Patrick that my bet is that this is caused by the threading/locking issue...

**Comment by adamvillalobos** [comment]
Unfortunately its not the GC, seems to just be that the framerate varies/is limited on certain devices. Not a whole lot we can do about this.
