### ISSUE TITLE
Loading palette PNG to MOAITexture via MOAIImage not working.

### ISSUE THREAD

**Issue by Zoomulator** [moai/moai-dev#957]
More troubles with palette pngs. Trying to load a png into MOAIImage first and then loading that into a texture doesn't work, while loading it by giving the path directly to MOAITexture.load works.

Using 1b927ece9bb18c68bf185fa76f1e373b5ceda6f6 on the 1.5-development branch.

Source reproducing the problem: http://pastebin.com/hVEg9qfm
Using PNG file: https://dl.dropboxusercontent.com/u/10564245/pin.png
Should show one black prop with the failed load and a second with the 'directly' loaded prop.

**Comment by halfnelson** [comment]
This seems to be working correctly as of 1.7. thanks for the report
