### ISSUE TITLE
Suggestion: use git to push code to the server, Heroku-style.

### ISSUE THREAD

**Issue by pygy** [moai/moai-dev#97]
It's all in the title. This is far more convenient than using a zip file for the upload.

**Comment by patrickmeehan** [comment]
Rob - pretty sure this is already in your roadmap.

**Comment by larubbio** [comment]
Yes, I completely agree and want this for myself.  It's on our roadmap.  I would also love some github integration so instead of having to push from a local machine you could just issue a pull from a branch.  I'd also love some integration with an online editor like http://c9.io/

**Comment by pygy** [comment]
[The luafuse memfs example](http://code.google.com/p/luafuse/source/browse/#svn%2Ftrunk) could easily be adapted to use MongoDB (and possibly GridFS), by modifying the mnode code.

**Comment by makotok** [comment]
MOAI Cloud ended. Close.
