### ISSUE TITLE
Segmentation Fault seemingly related to loading ttf fonts

### ISSUE THREAD

**Issue by matthewdpace** [moai/moai-dev#977]
The [code linked here](https://gist.github.com/matthewdpace/8ea91f51a46c0d6880f5) produces segmentation faults on OSX.
- Tested with both SDL and GLUT hosts
- Tested with two different fonts each ('Anonymous_Pro_B.ttf' and 'coolvetica.ttf')
- I can't remember exactly which build I'm on, but it was from the 1.5-stable branch, and downloaded/compiled about a month ago, maybe a little less.
- Stack trace and other information [linked here](https://gist.github.com/matthewdpace/99f06f8ca9b7f2060b5c).
- vavius in IRC noted something similar albeit being related to not being in the same directory as main.lua (or whever the entry point is located).  This was tested with the shell being in the same directory as the source, with the font in the same directory (and in an external directory), and the MOAI host binary being elsewhere in the filesystem.

**Comment by halfnelson** [comment]
you might need to pm me the font files, I can't reproduce with the fonts I have

**Comment by halfnelson** [comment]
I even downloaded a coolvetica font I found on the web, but still had no luck.

**Comment by sclark39** [comment]
This may also be related to https://github.com/moai/moai-dev/issues/978 and not to the font itself.

**Comment by matthewdpace** [comment]
As of this morning, the test code I posted isn't segfaulting, but my project is.  I've verified font file locations, and it's string representation in the code.

Commenting out everything related to starting my debug window eliminates the segfault, so that's something.

I'm trying to debug it, I'll update if I can trace down what's causing this.

**Comment by matthewdpace** [comment]
My bad, error in my resource loader - it would load the font fine but wouldn't correctly copy it from cache to another table, so initial testing showed that it was loading fine, but the action of copying it to the debug window table wouldn't work, and when the debug window drawer tried to use it, it would crash per issue 978
