### ISSUE TITLE
MOAIFont:preloadGlyphs causes crash when a valid font has not been loaded

### ISSUE THREAD

**Issue by sclark39** [moai/moai-dev#978]
I am trying to run flower-samples but Moai is crashing. I tracked it down to this bit of script

```
function Font:init(path, charcodes, points, dpi)
    self:load(path)
    self.path = path
    self.charcodes = charcodes
    self.points = points
    self.dpi = dpi

    if charcodes and points then
        self:preloadGlyphs(charcodes, points, dpi)
    end
end
```

The path given doesn't point to a font that I actually have, and when preloadGlyphs is called, the moai exe crashes. Seems like it should error out in this case instead.

**Comment by halfnelson** [comment]
thanks again!
