### ISSUE TITLE
[Question] Required Android.mk?

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#999]
Required Android.mk?
Was discarded because it was able to build with CMake in V1.5.

https://github.com/moai/moai-dev/blob/develop/ant/libmoai/jni/Android.mk

**Comment by halfnelson** [comment]
hello! @makoto , patrick/zipline are restoring/rewriting the ndk-build
based build scripts for android. Don't worry the CMAKE ones are being
updated for the current branch and will continue to be maintained.

**Comment by makotok** [comment]
OK. Thank you. 

However, "build-android.sh" does not work. 
there is no "clean.sh", "build.sh", "make-host.sh". 

I would fix.

```
/Users/mkinoshita/moai-work/moai-dev-makotok/bin/build-android.sh ; exit;
makoto-air:~ mkinoshita$ /Users/mkinoshita/moai-work/moai-dev-makotok/bin/build-android.sh ; exit;
/Users/mkinoshita/moai-work/moai-dev-makotok/bin/build-android.sh: line 7: ./clean.sh: No such file or directory
```

**Comment by halfnelson** [comment]
make-host.sh has  been moved into a lua function that is called by moaiutil (https://github.com/moai/moai-dev/tree/develop/util) 
[code=bash]
moaiutil ant-host
[/code]

check that script out first. I think it creates the host (and compiles the lib?)

The start of my fixes/changes to the android build process are here: https://github.com/moaiforge/moai-sdk/tree/projects-1.6

in particular the bin/build-android-lib.bat to build the lib that can then be used with the gradle (android studio) host ( https://github.com/moaiforge/moai-sdk/tree/projects-1.6/host-templates/android/studio/MoaiTemplate )

which I was preparing in readiness for binary sdk release process.

**Comment by makotok** [comment]
Thank you for information. 
I wait for a while.
